### ISSUE TITLE
Problem importing gedcom file from ancestry.com Sept 20 2022

### ISSUE THREAD

**Issue by Trodfoot** [fisharebest/webtrees#4563] opened 2022-09-22 04:34 UTC
This is more a heads up for the devs and others that get this error. I looked but didn't see it mentioned anywhere. I downloded my gedcom file from the ancestry website before and had no problems. Now I get this error:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\xA7\xAC\x0A2...' for column `webtrees`.`wt_individuals`.`i_gedcom` at row 1 (SQL: insert into `wt_individuals` (`i_id`, `i_file`, `i_rin`, `i_sex`, `i_gedcom`) values (I212408472719, 10, I212408472719, F, 0 @I212408472719@ INDI 1 NAME Sarah Ann /Short/  2 GIVN Sarah Ann 2 SURN Short 2 NSFX  1 FAMC @F22@ 1 SEX F 1 BIRT 2 DATE 1849 2 PLAC Hartland Devon England 1 BAPM 2 DATE 17 JUN 1853 2 PLAC Water Orton, Warwickshire, England 2 SOUR @S634026345@ 3 _APID 1,2446::3624555 1 RESI 2 DATE 1851 2 PLAC Hartland, Devon, England 2 SOUR @S634026315@ 3 _APID 1,8860::6955296 1 RESI 2 DATE 1861 2 PLAC Hartland, Devon, England 2 SOUR @S634025737@ 3 _APID 1,8767::18978296 1 RESI 2 DATE 1871 2 PLAC Bideford, Devon, England 2 SOUR @S634025971@ 3 _APID 1,7619::10637900 1 DEAT 2 DATE 18 DEC 1930 2 PLAC Hartland, Devon, England 1 SOUR @S633308715@ 2 PAGE Ancestry Family Tree))

As you can see there is a weird string at the start. I used dbeaver to look at the data and what the string is the new icon ancestry uses to show that someone has done a dna test. Webtrees will not import the gedcom if that is there. I removed it and webtrees imported everything as normal.

Maybe the devs can put in the importer a check for this and remove it so the import can complete. As not everyone can go into a db and make changes. Or if really ambitious add a indication on the persons page that they had a dna test done.

**Comment by fisharebest** [comment] 2022-09-22 06:58
webtrees doesn't currently support 4 byte UTF8 characters - this is being addressed in #2950

We also need to make remove the dependency on MySQL collation rules, as we also need to support other databases.

These fixes will probably be rolled out together.

**Comment by DaPoHou** [comment] 2022-09-23 01:01
Really looking forward to seeing a fix soon.

**Comment by fisharebest** [comment] 2022-09-24 10:12
Closing as duplicate of #2950

**Closed** 2022-09-24 10:13 UTC
