### ISSUE TITLE
Automatic reordering of children

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#4671] opened 2022-12-18 12:53 UTC
When adding a child in an existing family, children are not automatically  reordered according to their birth dates.

**Comment by LarsRabe** [comment] 2022-12-18 15:50
duplicate of #4511

**Comment by ghezibde** [comment] 2022-12-18 22:10
duplicate of https://github.com/fisharebest/webtrees/issues/4511

**Closed** 2022-12-18 22:10 UTC
