### ISSUE TITLE
Configure map provider error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3862] opened 2021-04-28 15:37 UTC
Control panel - All modules - Map providers 

Attempting to configure Mapbox or OpenStreetMap (what is there to configure in OpenStreetMap?) results in the following error message
```
View file not found: …\app/../resources/views/modules/mapbox/config.phtml …\app\View.php:266
#0 …\app\View.php(189): Fisharebest\Webtrees\View->getFilenameForView('modules/mapbox/...')
#1 …\app\View.php(286): Fisharebest\Webtrees\View->render()
#2 …\app\Helpers\functions.php(203): Fisharebest\Webtrees\View::make('modules/mapbox/...', Array)
#3 …\app\Http\ViewResponseTrait.php(51): view('modules/mapbox/...', Array)
#4 …\app\Module\MapBox.php(71): Fisharebest\Webtrees\Module\AbstractModule->viewResponse('modules/mapbox/...', Array)
#5 …\app\Http\RequestHandlers\ModuleAction.php(88): Fisharebest\Webtrees\Module\MapBox->getAdminAction(Object(Nyholm\Psr7\ServerRequest))
#6 …\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle(Object(Nyholm\Psr7\ServerRequest))
#7 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …\app\Module\HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 …\app\Http\Middleware\CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#11 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 …\app\Http\Middleware\Router.php(151): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#14 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …\app\Http\Middleware\BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 …\app\Http\Middleware\LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#21 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
```

**Comment by fisharebest** [comment] 2021-04-29 12:04
I was encouraged by another developer to push new code early, rather than wait for it to be 100% complete/tested.

Perhaps this isn't a good idea...

> what is there to configure in OpenStreetMap?

OSM provides three layers - mapnik/french/german.

I was assuming that users may only want one of these to be enabled?

**Comment by fisharebest** [comment] 2021-07-17 08:15
Duplicate of #3957

**Closed by fisharebest** 2021-07-17 08:15 UTC
