### ISSUE TITLE
dev - mouse over icon text

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1586] opened 2018-01-19 14:40 UTC
Demo site, mouse over icon in Pedigree root

![image](https://user-images.githubusercontent.com/5147603/35155756-faa880b4-fceb-11e7-88e3-eb870e1af303.png)

**Comment by fisharebest** [comment] 2018-01-19 22:47
I think this is already reported in another issue.

By default, the select2 library uses the content of the option as a tooltip.

I don't know why (it seems fairly pointless)
I don't know how to disable it or override it..

Not certain that we'll continue using select2.  There's another issue which reports poor accessibility, and suggests using the chosen library instead.

**Comment by maekclena** [comment] 2018-05-22 21:32
Select2 will carry over the `title` attribute from the `Option` element (see [here ](https://github.com/select2/select2/blob/c90adc102b5e9b2faea2b871b1c764416584ee07/src/js/select2/selection/single.js#L96) and [here](https://github.com/select2/select2/blob/c90adc102b5e9b2faea2b871b1c764416584ee07/tests/a11y/selection-tests.js#L12)).
The following should then work:
```javascript
opt = new Option(text, id);
opt.setAttribute('title', 'Click to select an individual');
$(select).select2().append(opt);
```

**Comment by fisharebest** [comment] 2018-07-16 19:14
Duplicate of #1316

**Closed by fisharebest** 2018-07-16 19:14 UTC
