### ISSUE TITLE
RTL Issues - 2.0.11-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3574] opened 2020-10-30 15:56 UTC
Greg, 

You said that the RTL issues of wt post 2.0.0 will be solved in 2.1.
When do you think this will take place?

For now I cannot update my live site to post 2.0.0 code because of too many RTL open issues and moreover for instance the local language changes do no longer work in my pre 2.0.0 code live site.

I have waited for a long time, if I am not mistaken since 2017.

**Comment by melizaa** [comment] 2021-06-04 14:15
When will the wt RTL issues get a solution?

**Comment by fisharebest** [comment] 2021-08-18 11:22
> You said that the RTL issues of wt post 2.0.0 will be solved in 2.1.

Many of the RTL issues are caused by issues in the Bootstrap library.  Bootstrap has been promising RTL support for a long time.  It is finally available in bootstrap 5, and I upgraded to it today.

This fixes most of the issues, and will be included in webtrees 2.1.0

**Closed by fisharebest** 2021-08-18 11:22 UTC
