### ISSUE TITLE
In user administration, sorting users on date "Last signed in" is broken

### ISSUE THREAD

**Issue by db-inf** [fisharebest/webtrees#1565] opened 2018-01-03 16:36 UTC
webtrees 1.7.9 module admin_users.php
Sorting on date  "Last signed in" does not work.
Sorting on "Date registered" is only ascending.
Sorting on the other columns is OK.

**Comment by fisharebest** [comment] 2018-01-06 17:52
Duplicate of #1157 - already fixed

**Closed by fisharebest** 2018-01-06 17:52 UTC
