### ISSUE TITLE
Interactive tree, webtrees 2.1.11

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#4641] opened 2022-12-05 11:38 UTC
The issue of not updating in full screen mode persists in 2.1.11

**Comment by photon-flip** [comment] 2022-12-07 07:55
This is an important issue that needs a reasonably high priority as this will be such a great enhancement when it's working fully. 
David Dury is pretty clued up on this.

**Comment by fisharebest** [comment] 2022-12-07 09:30
I think this is a duplicate of issue  #4615

**Closed by fisharebest** 2022-12-07 09:30 UTC
