### ISSUE TITLE
Import custom thumbnails page selection 2 - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3044] opened 2020-02-02 16:52 UTC
Import custom thumbnails from webtrees version 1

Please add the page selection also to the bottom of the page

**Comment by fisharebest** [comment] 2020-02-15 22:26
We use the same template for all tables.

Top-left: pagination
Top-right: filter
Bottom-left: information
Bottom-right: page length

Pagination is at the top because some tables have rows with varying height.
With it at the top, it is easy to keep clicking "next".
At the bottom, it could be in a different position for each page.

**Comment by fisharebest** [comment] 2021-03-05 14:49
This is a duplicate of #3148

**Closed by fisharebest** 2021-03-05 14:49 UTC
