### ISSUE TITLE
List of branches runs into error in case of implex

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1363] opened 2017-09-12 07:55 UTC
webtrees 2.0dev using php 5.6.31.
Gedcom is a clipping cart of ancestors of a dead people (so, not a single living individual in it). Small tree but a complex one (look at [home page](http://gustine.eu/wt3/index.php?ctype=gedcom&ged=Riviere-LeDu1)).
When logged on, all lists of branches are correctly displayed. 
When logged off, [one branch](http://gustine.eu/wt3/branches.php?surname=Ménard&ged=Riviere-LeDu1) gets errors : 
/home/…/includes/session.php:137 /home/…/app/Controller/BranchesController.php:241 usort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("/home/…/app/Controller/BranchesController.php:241 usort(): Array was modified by the user comparison function") 
#1 /app/Controller/BranchesController.php:241 usort([array], '\\Fisharebest\\Webtrees\\Family::…') 
#2 /app/Controller/BranchesController.php:269 getDescendantsHtml([Individual I3244@1], [Family F1116@1]) 
#3 /app/Controller/BranchesController.php:174 getDescendantsHtml([Individual I2725@1]) 
#4 /branches.php:66 getPatriarchsHtml()

**Comment by Gustine** [comment] 2017-09-13 07:57
Rather, the problem seems to be with the "list of families" function (any surnames).
/home/…/includes/session.php:137 /home/…/app/Controller/IndividualListController.php:527 usort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("/home/…/app/Controller/IndividualListController.php:527 usort(): Array was modified by the user comparison function") 
#1 /app/Controller/IndividualListController.php:527 usort([array], '\\Fisharebest\\Webtrees\\GedcomRe…') 
#2 /famlist.php:235 families('THIBAULT', 'T', '', false)

**Comment by fisharebest** [comment] 2017-09-13 21:55
Can you test something.  Add three lines before line 527`usort($list...)` 

```
foreach ($list as $family) {
	// Workaround: PHP 5.6 triggers PHP warning "Array was modified by the user comparison function".
	$family->getMarriageDate()();
}
usort($list, '\Fisharebest\Webtrees\GedcomRecord::compare');
```

**Comment by fisharebest** [comment] 2017-09-13 22:01
AFAICT, this is a PHP bug that was introduced in a recent 5.6.XXX release.
https://bugs.php.net/bug.php?id=50688

Since PHP 5.6 is out of support, it won't be fixed.

We use these sort functions in many places.  It will be inconvenient if we must add this workaround code everywhere.

**Comment by Gustine** [comment] 2017-09-14 07:32
I found « usort($list, '\\Fisharebest\\Webtrees\\GedcomRecord::compare'); » three times. 
In app/Controller/IndividualListController.php, app/Functions/FunctionsDb.php and app/Query/QueryName.php.
I made changes* in the first, then in the two others. Same errors with  « List of branches »and « List of families».
*using $family->getMarriageDate(); instead of $family->getMarriageDate()();

**Comment by fisharebest** [comment] 2017-09-17 19:33
> *using $family->getMarriageDate(); instead of $family->getMarriageDate()();

Yes, my mistake.

> I made changes* in the first, then in the two others. Same errors with « List of branches »and « List of families».

Are you saying that we need this fix in many places - or are you saying that this fix does not work?

> Since PHP 5.6 is out of support, it won't be fixed.

I notice that half of webtrees users now use PHP 7.0 / 7.1....

**Comment by Gustine** [comment] 2017-09-18 09:24
On MY system, this fix don't work.
Never mind, I'll wait for php 7.

**Comment by fisharebest** [comment] 2017-09-18 10:13
> On MY system, this fix don't work.
> Never mind, I'll wait for php 7.

I cannot reproduce the problem on my own (5.6) server.
I can only guess at the solution and ask you to test it...

**Comment by Gustine** [comment] 2017-09-18 10:16
I am entirely at your disposal for testing. Do not hesitate.

**Comment by fisharebest** [comment] 2017-09-23 07:33
Do you have the php-xdebug module installed?

If so, do you also see the error if you remove it?

**Comment by fisharebest** [comment] 2017-09-24 09:36
Also, in `session.php`, we set `error_reporting()` differently for stable and dev releases.

Do you see the error messages which you disable `WT_DEBUG`?

**Comment by Gustine** [comment] 2017-09-24 10:22
1 - I don't find _php-xdebug_ (using phpinfo()).
2 - In session.php, I replaced line 68 with _define ('WT_DEBUG', 0);_
Same error when logged off (and still no error when logged on).

**Comment by fisharebest** [comment] 2017-09-24 16:10
Do you see the problem using the 1.7.9 release, as well as the 2.0.0-dev code?

I am curious that nobody has reported this in the stable 1.7.9 release.

**Comment by Gustine** [comment] 2017-09-24 16:17
No problem, neither with 1.7.9 release, neither 1.8.0dev until June 17.
Errors came with https://github.com/fisharebest/webtrees/compare/master%40%7B2017-06-16%7D...master%40%7B2017-06-17%7D

**Comment by fisharebest** [comment] 2017-09-30 09:29
The long-term plan is to migrate webtrees to the Laravel framework.
The current LTS version of Laravel requires PHP 7.0.
An increasing number of external libraries also require PHP 7.0

I have therefore decided that webtrees 2.0.0 will require PHP 7.0.

**Closed by fisharebest** 2017-09-30 09:29 UTC
