### ISSUE TITLE
github - Multiple trees, switching from one to another broken

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2627] opened 2019-10-14 12:38 UTC
See demo site.  If you select the Greek Mythology tree the results are not correct.

**Comment by makitso** [comment] 2019-10-14 18:25
When you switch from the default tree to another tree, the default tree data is still shown on the home page, e.g. Surnames, Statistics, etc.

**Comment by bmhm** [comment] 2019-10-15 06:29
I cannot reproduce this. I am constantly switching between:

* https://dev.webtrees.net/demo-dev/tree/mythology/
* https://dev.webtrees.net/demo-dev/tree/demo/

Both pages look fine to me. Do I need to log in? Or is there another page which you mean by "home page"?

**Comment by fisharebest** [comment] 2019-10-15 06:32
I think this was fixed in last night's update.

**Closed by fisharebest** 2019-10-15 06:32 UTC
