### ISSUE TITLE
1.7.2  "Undefined offset: 2"  Editing Name Fact

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#704] opened 2015-08-26 03:11 UTC
Recently upgraded to 1.7.2 Received error below each time I open up name fact to edit for 1 individual

#0 /edit_interface.php:2521 ErrorException("Undefined offset: 2")
#1 /edit_interface.php:1643 Fisharebest\Webtrees\print_indi_form()

![nameediterror](https://cloud.githubusercontent.com/assets/13973937/9484707/b7dc6eac-4b7d-11e5-814a-418762dfc799.png)

This has only occurred on 1 individual but consistently.  I tried several others and received no error.

http://behunt.net/ft/individual.php?pid=I1548&ged=hunt.ged

**Comment by fisharebest** [comment] 2015-08-26 07:01
Does this name record have a multi-line note or source-citation?

**Comment by eric215** [comment] 2015-08-27 01:05
yes - there was a multi-line simple note attached to the Name fact.

I reproduced this in the current beta by adding a note line this

>1 NAME Augustus the Younger, Duke of Brunswick-Lüneburg
>2 NOTE line 1
>3 CONT line 2
>3 CONT line 3

With a one-line note the edit window works OK.

Adding a multi-line shared note does not cause a problem. The below works OK on my 1.7.2 site even though the shared note is several lines long

>1 NAME Douglas Wright /Hunt/
>2 TYPE birth
>2 GIVN Douglas Wright
>2 SURN Hunt
>2 NOTE @N133@

**Do you want this split into 2 bugs?**

The edit window fails on my 1.7.2 site and on the latest beta with the same message if the Text in the *source citation* is multi-lines as well: 

>1 NAME Douglas Wright /Hunt/
>2 TYPE birth
>2 GIVN Douglas Wright
>2 SURN Hunt
>2 NOTE @N133@
>2 SOUR @S15@
>3 DATA
>4 TEXT line 1
>5 CONT line 2
>5 CONT line 3

**Comment by fisharebest** [comment] 2015-08-27 06:37
> Do you want this split into 2 bugs?

No.  I think this is the same bug.

**Comment by antilet** [comment] 2015-09-01 07:58
Same bug in dev-demo (latest beta):
#0 /edit_interface.php:2521 ErrorException("Undefined offset: 2") 
#1 /edit_interface.php:1643 Fisharebest\Webtrees\print_indi_form('update', [Individual i229@1], [NULL], [Fact c0ba7de8db845acf11d4435822812704@i229], '', 'F')

also reported in forum:
https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-2/30629-error-by-editing-names#55113

is there an "easy" soution / workaround?

**Comment by fisharebest** [comment] 2015-09-04 18:06
Duplicate of #690

**Closed by fisharebest** 2015-09-04 18:06 UTC
