### ISSUE TITLE
github - import of place data (global.csv) that contains long and latitude, does not populate database table

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3690] opened 2021-01-24 17:42 UTC
I exported my places data two ways, with a csv file and a json file.  Both files contains Latitude and Longitude data.
When I import the json file all the Latitude and Longitude data is populated.  If I import the csv file the Latitude and Longitude is not populated regardless of the options used.

**Comment by fisharebest** [comment] 2021-01-25 13:48
This works for me.

The same code is used to import data, whether or not it came from a CSV or a GEOJSON file.

Can you show me an example from the CSV file?

**Comment by makitso** [comment] 2021-01-25 13:53
I sent you a .csv file

**Comment by fisharebest** [comment] 2021-01-25 14:07
> I sent you a .csv file

It didn't arrive.  Try again?

**Comment by makitso** [comment] 2021-01-27 00:38
https://www.webtrees.net/index.php/en/forum/help-for-2-0/35016-coordinates-are-not-imported#81006

https://www.webtrees.net/index.php/en/forum/help-for-2-0/34743-how-to-use-the-geographic-data-module#79229

**Comment by ddrury** [comment] 2021-01-27 16:13
Just thinking out loud here. Was the file you're trying to import created before Greg committed https://github.com/fisharebest/webtrees/commit/29395507e52962534ff9be5c06a6fc238f3ad23b? If so I wonder if the csv import routine also needs to handle orphaned records

**Comment by fisharebest** [comment] 2021-01-27 16:18
@ddrury - the .CSV file contained co-ordinates with the hemisphere as a suffix, not a prefix.
i.e. `1.23456N` instead of `N1.23456`.

We haven't established how exactly the file was generated.

I don't think it came from a stable release of webtrees - but it might have come from a dev version, and hence caused by a now-fixed bug.

On that basis, I'll leave this.  @makitso has cleaned up his file, and there are no other reports like it.

**Closed by fisharebest** 2021-01-27 16:18 UTC

**Comment by ddrury** [comment] 2021-01-27 16:24
Ah, that was one of the bugs I fixed. GedcomService used the following `private const DEGREE_FORMAT  = ' % .5f%s';`

**Comment by fisharebest** [comment] 2021-01-27 16:58
I just tested `2.0.11`, `2.0.10` and `2.0.9`.  All produce the correct output (i.e. suffix).

So I presume the code that you fixed wasn't actually being used to create the CSV export...

**Comment by makitso** [comment] 2021-01-27 17:04
All this leaves me confused.  If I load, via table import, the wt_placelocation, it look like this in phpmyadmin.

![image](https://user-images.githubusercontent.com/5147603/106024589-299cf080-6085-11eb-994d-2654d988e02f.png)

However, it throws the error PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'latitude' at row 1 in /home/rob/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117.

If I import with the S prefix then it works correctly.

**Comment by ddrury** [comment] 2021-01-27 18:27
Placelocation was changed to place-location (or place_location - can't remember) and the fields were changed. It looks like the last schema update hasn't been applied
