### ISSUE TITLE
2.0.15 - Notes to associates are not displayed

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3876] opened 2021-05-03 05:31 UTC
For marriages it is possible to add a note to the associates, but this note will not be displayed.

Is this a bug?

If not, where does that note appear?

**Comment by ro-la** [comment] 2021-05-14 09:26
This is a very old feature/bug/enhancement request - there are at least this two open issues regarding this (or a very similar issue)
https://github.com/fisharebest/webtrees/issues/3074
https://github.com/fisharebest/webtrees/issues/1284

**Comment by fisharebest** [comment] 2021-05-24 12:36
This is a duplicate of #1284

**Closed by fisharebest** 2021-05-24 12:36 UTC
