### ISSUE TITLE
I cannot add facts to the All individual facts list. GitHub code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1096] opened 2016-09-10 16:54 UTC
I tried to add _DNA to my family-trees All individual facts list.
I have added in the past some facts to the list.
The window did not allow me to add the full text _DNA without removing an existing fact.

My list is now:
BIRT,CHR,DEAT,BURI,CREM,ADOP,BAPM,BARM,BASM,BLES,CHRA,EMAIL,FAX,ORDN,NATU,EMIG,IMMI,CENS,WILL,GRAD,RETI,CAST,DSCR,EDUC,NATI,NCHI,NMR,OCCU,PROP,RELI,RESI,SSN,TITL,SLGC,_MILI,ASSO,_HNM,_HOL,FACT,DATA,_MTNG,_TODO,_NMAR,WWW,_ADPF,_ADPM,COMM,PHON,_NMR,_DNA

I removed ADDR from the list.

Meliza

**Comment by fisharebest** [comment] 2016-09-16 12:50
> The window did not allow me to add the full text _DNA without removing an existing fact.

We store the preferences in a database column that has a maximum size of 255 characters.

We can't increase this, due to the maximum size of MySQL indexes.

> The window did not allow me to add the full text _DNA without removing an existing fact.

This is by design.  The edit page will not allow you to enter a value that will not fit in the database.

This cannot be fixed without a significant redesign of the code (create a new table for fact types).

TIP: some of these facts (e.g. BIRT, DEAT, BURI, CREM, BARM, etc.) should only occur once.  You can move them from the "all facts" list to the "unique facts" list.

**Closed by fisharebest** 2016-09-16 12:50 UTC

**Comment by melizaa** [comment] 2016-09-18 10:42
Thanks for the explanation.

For now I moved CREM.

I have in the file more than one occurrence of the other tags that you mention. 

Meliza
