### ISSUE TITLE
GEDCOM import failed

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3872] opened 2021-04-30 11:38 UTC
Trying to import a GEDCOM-file with name "úvod-2021-04-28.ged" brings these messages:

`File not found at path: vod-2021-04-28.ged …/vendor/league/flysystem/src/Filesystem.php:389

#0 …/vendor/league/flysystem/src/Filesystem.php(194): League\Flysystem\Filesystem->assertPresent('vod-2021-04-28....')

#1 …/app/Http/RequestHandlers/ImportGedcomAction.php(96): League\Flysystem\Filesystem->readStream('vod-2021-04-28....')

#2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ImportGedcomAction->handle(Object(Nyholm\Psr7\ServerRequest))

#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))

#4 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(174): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))

#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))

#6 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))

#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))

#8 …/app/Http/Middleware/AuthManager.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))

...`

It seems the procedure is ignoring the first letter (which is accented).

A file-name "uúvod.ged" is accepted without problem. So it is only a problem with the first character.

Ladislav

PS. I know, it is not a good idea to have accented characters in filename.

**Comment by fisharebest** [comment] 2021-04-30 12:09
This works OK for me.

Tell me about your server.  Windows/Linux/Mac?  Version?  Filesystem type?

**Comment by ro-la** [comment] 2021-04-30 12:20
It is not my server, so I cann only give informations from phpinfo:

`PHP Version 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72

System: Linux c-php73.freesrv-01.XXXXXXXXX.sk 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64`

I cannot find nothing about the Filesystem type.

Which other informations do you need?

**Comment by fisharebest** [comment] 2021-04-30 13:26
> Which other informations do you need?

I do not know why this isn't working on your server.

I was guessing that you might be using a filesystem that does not support UTF8 characters.  But linux should be OK.

**Comment by ro-la** [comment] 2021-04-30 14:30
No it is not about general not supporting UTF8. It seems it has problems only with the very first character. There is no problem with export - I had  in the URL in tree preferences an UTF8 chracter - it worked everything. 

On other hand this cann be closed, as far as it seems to be a problem related only to my server environment.

**Comment by fisharebest** [comment] 2021-05-01 18:26
> On other hand this cann be closed, as far as it seems to be a problem related only to my server environment.

I am still curious to learn the cause of this issue.

**Comment by ro-la** [comment] 2021-05-01 20:08
I tried to upload a media file with accented first letter, even with a blank in the file name. Everything went OK.

**Comment by fisharebest** [comment] 2021-06-30 15:20
I still cannot reproduce this.  As you say, the issue could be specific to your environment.

Since there is nothing I can do, we should close this issue.

**Closed by fisharebest** 2021-06-30 15:20 UTC
Labels: cannot reproduce
