### ISSUE TITLE
Error Timeline Chart?

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#832] opened 2016-02-12 18:02 UTC
/var/www/html/sk/skatekey.net/includes/session.php:191 /var/www/html/sk/skatekey.net/app/Theme/AbstractTheme.php:1078 Argument 1 passed to Fisharebest\Webtrees\Theme\AbstractTheme::menuChart() must be an instance of Fisharebest\Webtrees\Individual, null given, called in /var/www/html/sk/skatekey.net/app/Theme/AbstractTheme.php on line 1897 and defined
#0 /app/Theme/AbstractTheme.php:1078 ErrorException("/var/www/html/sk/skatekey.net/app/Theme/AbstractTheme.php:1078 Argument 1 passed to Fisharebest\Webtrees\Theme\AbstractTheme::menuChart() must be an instance of Fisharebest\Webtrees\Individual, null given, called in /var/www/html/sk/skatekey.net/app/Theme/AbstractTheme.php on line 1897 and defined")
#1 /app/Theme/AbstractTheme.php:1897 menuChart([NULL])
#2 /app/Theme/AbstractTheme.php:220 primaryMenu()
#3 /app/Controller/PageController.php:177 bodyHeader()
#4 /timeline.php:30 pageHeader()

**Comment by fisharebest** [comment] 2016-02-12 18:22
Duplicate of #830 ?

**Comment by makitso** [comment] 2016-02-12 18:25
On Dev, but yea, probably, sorry :-)

**Comment by fisharebest** [comment] 2016-02-12 18:27
No worries.

**Closed by fisharebest** 2016-02-12 18:27 UTC
