### ISSUE TITLE
Case Sensitivity in Update Place Names

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3458] opened 2020-08-02 14:29 UTC
When using the Data Fix to Update Place Names, the Search button and the Update button have two different behaviors.

If I have places named `Montreal` and I search for `Montréal` then I see several search results.

If I then try to update `Montréal` to a different name, it shows 100% progress but no changes have appeared in the database.

I also noted that by switching the search to `Montreal` I get the same results in the Record column, but instead of a blank Data fix column, I get buttons appearing in the Data fix column.  So why would I get the same results with different buttons?  This is very confusing for the user admin.

**Comment by fisharebest** [comment] 2021-02-27 09:42
There is a link at the bottom of the data-fix page:

> Why does this list include records that do not need to be updated?

I think it explains the situation you are describing.

When you search for `Montréal`, the initial search will pick it up (because the MySQL query ignores accents).

But when we find the record, there is nothing to update, as it contains `Montreal` instead of `Montréal`.

So this appears to be working as designed.

I understand that the design is a bit clunky - but we need a way to do lots of resource-intensive calculations on under-powered servers, and also have a user-interface that responds within a few seconds.

**Comment by fisharebest** [comment] 2021-11-06 21:54
I'm going to close this, as the code is working as designed.

**Closed by fisharebest** 2021-11-06 21:54 UTC
