### ISSUE TITLE
Markdown width

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#2814] opened 2019-12-02 21:32 UTC
When using markdown, census transcrips exceeds page width and goes under the sidebar
Should there be a scrollbar like in 1.7?
![censustranscript](https://user-images.githubusercontent.com/55854079/69997083-a997fb00-1553-11ea-833e-1f74578346fb.jpg)

**Comment by fisharebest** [comment] 2019-12-02 23:15
Duplicate of #1427

**Closed by fisharebest** 2019-12-02 23:15 UTC
