### ISSUE TITLE
Advanced Search for Place of Marriage not working

### ISSUE THREAD

**Issue by rgdobie** [fisharebest/webtrees#4887] opened 2023-10-03 03:02 UTC
Using the demo of the Royal Family, I searched for a Place of Marriage of 'City of Westminster, London, England'.  
I expected this to return the records for  Elizabeth II and her husband but instead got a 'no results found'.

**Comment by photon-flip** [comment] 2023-10-03 03:18
Seems like it doesn't like the punctuation. City of Westminster London England works. Maybe something to be improved.

**Comment by rgdobie** [comment] 2023-10-03 04:04
Wow, so quick, I am impressed!

 

There may be a further issue when people have been married more than once.

 

Searching without punctuation in my own tree (VERSION 2.1.17), I found:

. one person whose first marriage was found but not their second

. two persons whose second marriage was found but not the first

. one person whose first and second marriages were found.

 

Regards

Richard

**Comment by photon-flip** [comment] 2023-10-03 08:56
Hi Richard, my reply might have been quick but unfortunately I don't have a quick fix for this. Something for the PHP wizards to tackle.
MurrayJ

**Comment by magicsunday** [comment] 2023-11-30 07:09
I can't reproduce this. Looks good to me.

![grafik](https://github.com/fisharebest/webtrees/assets/564393/7d429935-8a3d-49a6-85e7-391b0abdbf67)

**Comment by fisharebest** [comment] 2024-02-17 00:32
The search indexes are created for each level of a place-name.  Thus `City of Westminster, London, England` creates three separate indexes - `City of Westminster`, `London` and `England`.

The advanced search expects you to type one of these three.

Of course, this can lead to ambiguity.  For example `Georgia` will match both the country and the US state.

This is not very intuitive.  We can provide an input field with auto-complete that selects fully-qualified placenames.

**Closed** 2024-02-17 00:57 UTC
Labels: bug

**Comment by rgdobie** [comment] 2024-02-17 02:55
Hi fisharebest, further to this I logged into the Royal Family as moderator:
I changed the place of marriage for Elizabeth II to sydney, new south wales, australia.
I advance searched for place of marriage of sydney. No result.

I changed the place of birth for Elizabeth II to newcastle,  new south wales, australia
I advance searched for place of marriage of sydney. No result.

I changed the place of birth for Elizabeth II to  sydney, new south wales, australia
I advance searched for place of marriage of sydney.  and the record for Elizabeth II was returned.

Is it  possible that for marriages the wrong index is being searched (i.e. the birth index instead of the marriage index)?

Thanks,
Regards
Richard

**Comment by fisharebest** [comment] 2024-02-17 11:17
It looks like the update-script on the demo server had crashed, so you weren't seeing the new code.

Try again now.  Searching for "born in greece" and "married in england" gives the Duke of Edinburgh, as expected.

**Comment by rgdobie** [comment] 2024-02-17 19:20
Hmm...When I advance search for place of marriage as CIty of Westminster I get 5 marriages but in the Marriages report, I get 8.

**Comment by fisharebest** [comment] 2024-02-19 00:30
That looks like a copy/paste error in the code.  Fixed.

We now see 16 in the search (because it finds individuals) and 8 in the report (because it finds families).

**Comment by rgdobie** [comment] 2024-02-20 21:40
Just tried in the latest Beta. That looks much better (though I got 18 and 9 hits rather than 16 and 8) and the dropdown is a nice touch.
There may be an issue with the dates as well.
I searched with a date of birth of LONDON (ridiculous input, I know) but I got 206 hits.
I tried with a DOB of DEC and also got 206 hits. 14 DEC also gave 206 hits.
DEC 1895 gave one hit as did 14 DEC 1895.
