### ISSUE TITLE
In php7, set_exception_handler takes Throwable, not Exception

### ISSUE THREAD

**Issue by jernst** [fisharebest/webtrees#821] opened 2016-01-31 07:34 UTC
See http://php.net/set_exception_handler

Details:

[UBOS](http://ubos.net/) currently [supports](https://github.com/uboslinux/ubos-webtrees) webtrees 1.6.2 with php5. We are in the process of upgrading to php7 and webtrees 1.7.3. I'm getting the following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Fisharebest\\Webtrees\\{closure}() must be an instance of Fisharebest\\Webtrees\\Exception, instance of Error given in /srv/http/sites/s39e310197fcc08d9ad1cb5bba3ca8ad818a2d9c2/ctxt-2232b5de/includes/session.php:197
Stack trace:
#0 [internal function]: Fisharebest\\Webtrees\\{closure}(Object(Error))
#1 {main}\n  thrown in /srv/http/sites/s39e310197fcc08d9ad1cb5bba3ca8ad818a2d9c2/ctxt-2232b5de/includes/session.php on line 197
```

This looks like an error that occurred during error reporting, and by removing parameter type Exception in that line makes the error-during-error-reporting go away.

**Comment by fisharebest** [comment] 2016-01-31 13:59
This was changed a few days ago.

https://github.com/fisharebest/webtrees/blob/master/includes/session.php#L194

**Comment by fisharebest** [comment] 2016-01-31 14:02
Duplicate of https://github.com/fisharebest/webtrees/issues/792

**Closed by fisharebest** 2016-01-31 14:02 UTC
