### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by jcvignoli** [fisharebest/webtrees#3634] opened 2020-12-21 19:50 UTC
Webtree is not compatible with PHP 8.

**Comment by fisharebest** [comment] 2020-12-21 19:56
The problem is not with webtrees - but with the third-party libraries that it uses.

In particular, [`doctrine/dbal`](https://github.com/doctrine/dbal) does not support PHP 8.0 until version 3 - and version 3 drops support for PHP 7.2.

So, to support PHP 8.0, webtrees would need to drop support for PHP 7.2.

Although PHP 7.2 is [end-of-life](https://www.php.net/supported-versions.php), it is still used by approx [25% of webtrees users](https://dev.webtrees.net/statistics.html).

**Comment by HonkXL** [comment] 2020-12-22 14:28
But most of these users would have no problems to switch from legacy-builds of PHP to up to date versions...

**Comment by jcvignoli** [comment] 2020-12-22 14:34
It might take time to make webtree fully PHP 8 compatible. The earliest one starts, the safer it is.

And that's a useless debate: professional servers will soon start upgrading progressively to PHP 8. Only home hosted servers may stay on PHP 7 longer.

**Comment by Lars1963** [comment] 2020-12-23 15:21
The best way imho is to drop php 7.2 and support php 8.0 with the upcoming WT 2.1 release and leave 2.0.x as is.

**Comment by HonkXL** [comment] 2021-01-15 15:23
I think this sounds good. Security Support for 7.4 ends on 28. Nov 2022. This is the latest date to provide 8.0 compatibility.

**Comment by fisharebest** [comment] 2021-01-15 17:23
> The best way imho is to drop php 7.2 and support php 8.0 with the upcoming WT 2.1 release and leave 2.0.x as is.

FYI, the 2.1 branch of the code is currently waiting for

* an update to the TCPDF library to support PHP 8.0.  Patches have been written, but not yet merged into the code.
* a response to my issue on the Flysystem 2.0 library, as the version which supports PHP 8 does not currenlty allow you to distinguish files and folders.

Everything else seems to work OK - so hopefully soon.

**Comment by Lars1963** [comment] 2021-01-16 10:09
> Everything else seems to work OK - so hopefully soon.

@fisharebest  That's fine. 👍

I haven't looked in the 2.1-branch yet, but will it drop support for php 7.2 and mark 7.3 as deprecated? I'll setup a testing-instance for the 2.1-branch these days. 😀

**Comment by fisharebest** [comment] 2021-01-16 10:15
> but will it drop support for php 7.2

Yes.  It will drop support for 7.1 and 7.2

> mark 7.3 as deprecated?

No.  There is no need to do this.  PHP 7.3 will receive security updates for another 11 months.
Supporting it creates no problems for us.

**Comment by DoctorSubtilis** [comment] 2021-01-31 17:01
+1 for compatibility with php 8

**Comment by fisharebest** [comment] 2021-05-14 14:50
PHP8 compatibility fixes have been merged into the main branch, and will be included in 2.1.0.

**Closed by fisharebest** 2021-05-14 14:50 UTC
Labels: bug
