### ISSUE TITLE
Geographic Data - item marked eligible for deletion in error

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3555] opened 2020-10-16 20:11 UTC
On the Geographical Data page, I have 1 item that is marked unused + eligible for deletion but it is in fact in use

Ver 2.0.9
 
![Capture](https://user-images.githubusercontent.com/13973937/96304278-d0bfb580-0fc9-11eb-8300-77e11515273d.JPG)

![Capture](https://user-images.githubusercontent.com/13973937/96304330-e8973980-0fc9-11eb-8a2d-cd740b08feaf.JPG)

**Comment by eric215** [comment] 2020-10-16 20:12
![Capture](https://user-images.githubusercontent.com/13973937/96304618-6c512600-0fca-11eb-9625-975c58a09f0a.JPG)

**Comment by fisharebest** [comment] 2020-10-16 20:18
This is possibly a duplicate of #3446,  which is caused by a mismatch of upper/lower case or letters with diacritic marks.

e.g. `Barton` / `BARTON` or `Quebec` / `Québec`.

Can you check to see if your data contains such a variation on `Barton`.

**Comment by eric215** [comment] 2020-10-16 21:07
Going from the Place Hierarchy, this is the only reference to Barton in Tioga County

![Capture](https://user-images.githubusercontent.com/13973937/96308827-0bc5e700-0fd2-11eb-9507-85749e34eadc.JPG)

**Comment by fisharebest** [comment] 2020-10-16 21:27
> Can you check to see if your data contains such a variation on `Barton`.

Can you check again for `Tioga County`?

**Comment by eric215** [comment] 2020-10-17 00:46
Place Hierarchy: 
![Capture](https://user-images.githubusercontent.com/13973937/96324439-e5af3f80-0fef-11eb-911e-f5f882c9ce54.JPG)

When I search the Places table for `SELECT * FROM `wt_places` WHERE p_place like '%barton%' or p_place like '%tioga%' `
 I get back just 2 rows:

![Capture](https://user-images.githubusercontent.com/13973937/96324597-974e7080-0ff0-11eb-8c48-91dd2fb90d19.JPG)


The parent, p_id 11115, is New York

**Comment by HRN65** [comment] 2020-10-17 17:50
There seem to be upper/lower case mismatch in "County"

**Comment by eric215** [comment] 2020-10-17 18:47
Correct - I didn't catch that earlier!   Shows on the Geographic Data page with a lower-case "c" for county; but in the individual record and on the Places table the "c" is capitalized.

**Comment by fisharebest** [comment] 2020-10-18 16:37
> There seem to be upper/lower case mismatch in "County"

Then this is a duplicate of #3446 

Best to continue that  discussion.

**Closed by fisharebest** 2020-10-18 16:37 UTC
