### ISSUE TITLE
Add Individual Sources from Clipboard in Sources tab

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1224] opened 2017-03-07 23:00 UTC
I would like to have the possibility to add (at least) individual source entries from the clipboard also on the Sources tab.

Now I need to check on the Sources tab if the source exists and then go to the Facts and events tab to add it.

**Comment by fisharebest** [comment] 2017-12-05 21:27
Duplicate of #860

**Closed by fisharebest** 2017-12-05 21:27 UTC
