### ISSUE TITLE
Thumbnail is rotated

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4405] opened 2022-05-14 03:57 UTC
The MacOS Finder shows both of these images correctly, as does a graphics editor when I open them directly.  When I click on the thumbnail, I get the correct full-size view.  Only the generated thumbnail is rotated.
<img width="223" alt="image" src="https://user-images.githubusercontent.com/5910274/168409901-27253d30-322b-4b6e-914a-0dbccc5508d8.png">

**Comment by fisharebest** [comment] 2022-05-14 07:49
This appears to be a duplicate of #4252

**Closed by fisharebest** 2022-05-14 07:49 UTC
