### ISSUE TITLE
2.0 Error when importing places.csv

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#1930] opened 2018-09-24 18:25 UTC
ErrorException: Undefined offset: -3 in file /app\Http\Controllers\AdminLocationController.php on line 383
Stack trace:
  1. ErrorException->() /app\Http\Controllers\AdminLocationController.php:383
  2. Fisharebest\Webtrees\{closure}() /app\Http\Controllers\AdminLocationController.php:383
  3. Fisharebest\Webtrees\Http\Controllers\AdminLocationController->importLocationsAction() [internal]:0
  4. ReflectionMethod->invoke() /app\Resolver.php:85
  5. Fisharebest\Webtrees\Resolver->dispatch() /index.php:324
  6. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\CheckForMaintenanceMode.php:48
  7. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:319
  8. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\UseTransaction.php:46
  9. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:319
 10. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\CheckCsrf.php:48
 11. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:319
 12. Fisharebest\Webtrees\{closure}() /index.php:327
 13. call_user_func() /index.php:327

**Comment by fisharebest** [comment] 2018-09-24 18:36
This is a duplicate of #1896 which is already fixed.

The fix will be included in the alpha.3 release

**Comment by HRN-webtrees** [comment] 2018-09-24 18:50
in today's dev I get the following error

PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Ikon' for column 'pl_zoom' at row 1 in file /app\Statement.php on line 85
Stack trace:
  1. PDOException->() /app\Statement.php:85
  2. PDOStatement->execute() /app\Statement.php:85
  3. Fisharebest\Webtrees\Statement->execute() /app\Location.php:208
  4. Fisharebest\Webtrees\Location->add() /app\Http\Controllers\AdminLocationController.php:456
  5. Fisharebest\Webtrees\Http\Controllers\AdminLocationController->importLocationsAction() [internal]:0
  6. ReflectionMethod->invoke() /app\Resolver.php:85
  7. Fisharebest\Webtrees\Resolver->dispatch() /index.php:321
  8. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\CheckForMaintenanceMode.php:48
  9. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:316
 10. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\UseTransaction.php:46
 11. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:316
 12. Fisharebest\Webtrees\{closure}() /app\Http\Middleware\CheckCsrf.php:48
 13. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:316
 14. Fisharebest\Webtrees\{closure}() /index.php:324
 15. call_user_func() /index.php:324

**Comment by fisharebest** [comment] 2018-09-24 18:53
Can you post the first two lines from the .CSV file

**Comment by HRN-webtrees** [comment] 2018-09-24 18:56
![places](https://user-images.githubusercontent.com/7372415/45972570-5adffe80-c03c-11e8-96e2-f0c1fa962cb1.jpg)

**Comment by HRN-webtrees** [comment] 2018-09-24 19:02
"Level";"Country";"State";"County";"City";"Place";"Longitude";"Latitude";"Zoom level";"Icon";
0;Canada;;;;;W104;N54;2;
1;Canada;British Columbia;;;;W125;N54.5;5;
2;Canada;British Columbia;Surrey;;;W122.80;N49.10;12;
2;Canada;British Columbia;Vancouver;;;W123.1;N49.24;9;

**Comment by fisharebest** [comment] 2018-09-24 19:17
The code assumes the header comments are written in English.

If the first line starts with "Level", then the line is skipped.

It looks like the first line in your file contains "Level" in Norwegian.

I think we should change the test from "Level" to "non-numeric".

**Closed** 2018-09-24 19:19 UTC

**Comment by HRN-webtrees** [comment] 2018-09-24 19:27
I can confirm. Exporting/importing the file in english works fine
