### ISSUE TITLE
Age calculations for date ranges

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#3919] opened 2021-06-03 07:18 UTC
When the date of an event is recorded as a range, only the age at the lower limit is shown. But the age at the upper limit is of interest as well! Also it is confusing for readers, since they have to figure out whether the shown age is at the lower or at the upper limit, defeating the purpose.

Is it possible to show both? For instance:

between 1940 and 1960 (aged 33-53 years)

**Comment by fisharebest** [comment] 2021-07-27 10:30
This would be a duplicate of #3435

**Closed by fisharebest** 2021-07-27 10:30 UTC
Labels: enhancement
