### ISSUE TITLE
Fan chart shows Chinese characters are garbled

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2260] opened 2019-02-24 01:21 UTC
Whether it is version 1.7 or version 2.0, displaying Chinese characters in the fan chart is garbled.
Because of the lack of Chinese font files. So the display is garbled. Chinese font files are generally very large, generally greater than 10MB. Can the fan chart be displayed without a font file?
![default](https://user-images.githubusercontent.com/26761596/53293768-80ed1300-3815-11e9-8a1a-a90019b0acbd.JPG)

**Comment by fisharebest** [comment] 2019-02-24 08:55
Possibly the same issue as #1479

I guess that the DejuVu font file does not contain these characters.

**Comment by fisharebest** [comment] 2019-03-04 09:13
The font file does not contain Chinese characters.  Duplicate of #1479

**Closed by fisharebest** 2019-03-04 09:13 UTC
