### ISSUE TITLE
2.0 - bad links to favicons

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#1947] opened 2018-10-07 00:25 UTC
The 2.0 demo:
  htts://dev.webtrees.net/demo-dev/index.php?route=tree-page&ged=demo

includes this html:
```
<link rel="icon" href="themes/webtrees/css-2.0.0/favicon.png" type="image/png">
<link rel="icon" type="image/png" href="themes/webtrees/css-2.0.0/favicon192.png" sizes="192x192">
<link rel="apple-touch-icon" sizes="180x180" href="themes/webtrees/css-2.0.0/favicon180.png">
```

But all three of those image references return a 404. It looks like "themes/webtrees/" should be replaced with "themes/_common/"

**Comment by fisharebest** [comment] 2018-10-11 20:07
This appears to be a duplicate of #1780.

I'll look at the HTML/CSS and styling issues once I've finished with the alpha releases.

**Closed by fisharebest** 2018-10-11 20:07 UTC
