### ISSUE TITLE
Something is wrong with Place hierarchy at mobile screen

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3671] opened 2021-01-14 17:25 UTC
Block of map is overlapping.

**Comment by JustCarmen** [comment] 2021-01-16 15:33
I think this is a duplicate of https://github.com/fisharebest/webtrees/issues/3568

**Comment by mrqd9** [comment] 2021-01-16 15:37
> I think this is a duplicate of #3568

Correct.

**Closed** 2021-01-19 09:59 UTC
