### ISSUE TITLE
Relationship to me - route changes

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1587] opened 2018-01-20 15:34 UTC
When the route changes happened the related to me doesn't auto calculate based on the last viewed individual like it used to do?

**Comment by fisharebest** [comment] 2018-01-20 15:37
This affects all the header / menu items.

There are some other changes I need to make before I can fix this one.

**Comment by curtisdelicata** [comment] 2018-01-20 15:38
Thank you for reply.

**Comment by melizaa** [comment] 2018-02-27 08:53
Is this why I do not see any rlationship reports. The program just runs and runs. Also in demo-dev.

**Comment by fisharebest** [comment] 2018-02-27 15:05
> The program just runs and runs.

That's a different issue - which I've just fixed.

**Comment by fisharebest** [comment] 2018-03-02 22:09
This is a duplicate of #1608

**Closed by fisharebest** 2018-03-02 22:09 UTC
Labels: bug
