### ISSUE TITLE
Unable to find relationship between two individuals on strato.de hosted webtrees using SunOS

### ISSUE THREAD

**Issue by exxamalte** [fisharebest/webtrees#697] opened 2015-08-25 00:06 UTC
The relationship calculation between two individuals fails, i.e. always returns with the message "No link between the two individuals could be found", on SunOS and PHP 5.6.
This issue happens irrespective of the distance of the relationship; e.g. even parent-child relationships produce the above message, and even though the relationship is correctly stored in the database and displayed correctly on the individuals' and family's pages.

The Dijkstra algorithm code uses a constant `INF` which appears to be misinterpreted as `float(0)` on that platform. Hence, the algorithm does not work anymore and no paths can be found.

This PHP bug appears to be related to this issue: https://bugs.php.net/bug.php?id=69188

Here is the original discussion in the forum https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-2/30583-relationship-to-me where two users reported the issue on the following platforms:
- Apache/2.2.29 (SunOS 5.10), PHP 5.6.10
- SunOS localhost 5.10 Generic_142901-13 i86pc and PHP is version 5.6.10 (provided by hoster Strato)

A simple workaround for the Dijkstra code on the affected platforms is to use a very high integer (e.g. `PHP_INT_MAX`) instead of `INF`.

**Comment by fisharebest** [comment] 2015-08-25 12:48
I have created a SunOS 11.2 system (using virtualbox), and installed all the tools necessary to build PHP.

I then run the test script from the [bug report](https://bugs.php.net/bug.php?id=69188)

```php
<?php
$v = INF;
var_dump($v);
$v = NAN;
var_dump($v);
```

The output is (as expected)
```
float(INF)
float(NAN)
```

I tried several PHP versions, including 5.6.12 and the latest development version.

So, the problem would appear to be with strato.de, and not with PHP/SunOS.

**Comment by exxamalte** [comment] 2015-08-25 22:17
Another user in the forum also reported in the meantime that PHP 5.6, 5.5 and 5.3 on SunOS with that particular hoster (strato.de) appear to be affected by the issue. I renamed the issue title.

**Comment by fisharebest** [comment] 2015-12-31 22:49
IIRC, somebody raised this with strato.de.  Has there been any progress?

**Comment by mtdcr** [comment] 2016-01-19 00:37
I'm facing the same problem on Ubuntu. Maybe I'll try to find the cause when I get some spare time. Can you give me a hint where to start debugging in the meantime?

**Comment by exxamalte** [comment] 2016-01-19 06:33
Originally the issue was only reported by users on hoster strato.de using SunOS. A PHP bug report also indicated that strato.de users are affected by the issue (independent of webtrees). 
Perhaps they are using a custom PHP version? Are you using a standard Ubuntu PHP package, or a custom version, i.e. one you compiled yourself? As a starting point you could try the test PHP script from above to formally reproduce the issue on your system.

**Comment by mtdcr** [comment] 2016-01-21 15:25
It appears to be a different problem: The PHP script works as intended. I'm trying to display the relationship between I1 and I3, both members of F1, but my wt_links database doesn't contain any links with l_from=F1, but for most other families. The database was started about 10 years ago. Maybe something went wrong during an upgrade. Is there a (semi-)automated way to check the database for consistency?

**Comment by fisharebest** [comment] 2016-01-21 15:36
> Is there a (semi-)automated way to check the database for consistency?

No - but if you export and import, it will rebuild all the index tables (e.g. wt_link).

**Comment by mtdcr** [comment] 2016-01-21 16:01
Thanks! Problem solved.

**Comment by fisharebest** [comment] 2016-01-23 22:58
This is now fixed - through an update to the library `fisharebest/php-polfill`.

**Closed by fisharebest** 2016-01-23 22:58 UTC
