### ISSUE TITLE
Dispalay of db credentials

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3194] opened 2020-04-27 12:06 UTC
I patched my site with https://github.com/fisharebest/webtrees/commit/ff020ee8fd4f98bee76bf37178140a4da67a4dcb 13 april, and was surprised to se my db credentials displayed during a transient db problem this weekend

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1040] Too many connections in /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27 Stack trace: #0 /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=XXXX', 'XXXXXXX', 'XXXXXXXXXX', Array) #1 /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=XXXX', 'XXXXXXX', 'XXXXXXXXXX', Array) #2 /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=XXXX', 'XXXXXXX', 'XXXXXXXXXX', Array) #3 /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/illuminate/database/C in /storage/content/50/100750/xxxxx.com/public_html/webtree/vendor/illuminate/database/Connection.php on line 664

**Comment by fisharebest** [comment] 2020-04-27 12:08
Duplicate of #3102 - already fixed.

**Comment by fisharebest** [comment] 2020-04-27 12:09
Re-opening - sorry - didn't read all the details...

**Comment by fisharebest** [comment] 2020-04-27 12:12
Is that the full stack dump?

If not, can you post it all?

**Comment by HRN65** [comment] 2020-04-27 12:22
This is all that was displayed on the screen. I find nothing in logs.

**Comment by HRN65** [comment] 2020-04-27 12:35
Here is one from 8 april (before I patched my site)

PDOException: SQLSTATE[HY000] [1040] Too many connections in /storage/content/50/100750/mysite.com/public_html/webtree/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27 Stack trace: #0 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=wt20...', 'XXXXXXX', 'XXXXXXXXXX', Array) #1 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=wt20...', 'XXXXXXX', 'XXXXXXXXXX', Array) #2 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=wt20...', 'XXXXXXX', 'XXXXXXXXXX', Array) #3 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=wt20...', Array, Array) #4 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() #6 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(919): call_user_func(Object(Closure)) #7 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(452): Illuminate\Database\Connection->getPdo() #8 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('create table `w...', Array) #9 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('create table `w...', Array, Object(Closure)) #10 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('create table `w...', Array, Object(Closure)) #11 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('create table `w...') #12 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar)) #13 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint)) #14 /storage/content/50/100750/mysite.com/public_html/webtree/app/Schema/Migration0.php(44): Illuminate\Database\Schema\Builder->create('gedcom', Object(Closure)) #15 /storage/content/50/100750/mysite.com/public_html/webtree/app/Services/MigrationService.php(69): Fisharebest\Webtrees\Schema\Migration0->upgrade() #16 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 44) #17 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDatabase.php(106): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BadBotBlocker.php(208): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #35 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /storage/content/50/100750/mysite.com/public_html/webtree/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #43 {main} Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1040] Too many connections in /storage/content/50/100750/mysite.com/public_html/webtree/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31 Stack trace: #0 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=wt20...', 'XXXXXXX', 'XXXXXXXXXX', Array) #1 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=wt20...', 'XXXXXXX', 'XXXXXXXXXX', Array) #2 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=wt20...', Array, Array) #3 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() #5 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(919): call_user_func(Object(Closure)) #6 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(452): Illuminate\Database\Connection->getPdo() #7 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('create table `w...', Array) #8 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('create table `w...', Array, Object(Closure)) #9 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('create table `w...', Array, Object(Closure)) #10 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('create table `w...') #11 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar)) #12 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint)) #13 /storage/content/50/100750/mysite.com/public_html/webtree/app/Schema/Migration0.php(44): Illuminate\Database\Schema\Builder->create('gedcom', Object(Closure)) #14 /storage/content/50/100750/mysite.com/public_html/webtree/app/Services/MigrationService.php(69): Fisharebest\Webtrees\Schema\Migration0->upgrade() #15 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 44) #16 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDatabase.php(106): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BadBotBlocker.php(208): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /storage/content/50/100750/mysite.com/public_html/webtree/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #42 {main} Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1040] Too many connections (SQL: create table `wt_gedcom` (`gedcom_id` int not null auto_increment primary key, `gedcom_name` varchar(255) not null, `sort_order` int not null default '0') default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB) in /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php:664 Stack trace: #0 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('create table `w...', Array, Object(Closure)) #1 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('create table `w...', Array, Object(Closure)) #2 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('create table `w...') #3 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar)) #4 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint)) #5 /storage/content/50/100750/mysite.com/public_html/webtree/app/Schema/Migration0.php(44): Illuminate\Database\Schema\Builder->create('gedcom', Object(Closure)) #6 /storage/content/50/100750/mysite.com/public_html/webtree/app/Services/MigrationService.php(69): Fisharebest\Webtrees\Schema\Migration0->upgrade() #7 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 44) #8 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseDatabase.php(106): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BadBotBlocker.php(208): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 /storage/content/50/100750/mysite.com/public_html/webtree/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /storage/content/50/100750/mysite.com/public_html/webtree/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /storage/content/50/100750/mysite.com/public_html/webtree/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #34 {main}

**Comment by fisharebest** [comment] 2020-04-28 21:35
> I patched my site with ff020ee

Does this mean that you just installed this commit, or that you installed all commits up to this one?

IIRC, this fix was implemented in more than one commit. ff020ee was just the last one.

**Comment by HRN65** [comment] 2020-04-29 06:47
I'm "sure" I installed all commits, but could have missed one. Will install latest code, and report back if it happens again.

**Comment by HRN65** [comment] 2020-05-03 07:03
With latest code (as of 1st May) I see the same message

**Comment by fisharebest** [comment] 2020-05-04 12:05
OK, I see the problem now.

We catch the error OK, but we try to log it (in the database) - which triggers it again.

**Closed** 2020-05-04 14:22 UTC
