### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3752] opened 2021-03-01 18:58 UTC
In many cases dates of birth and death are unknown, but we do have dates for christening and burial from the parish records.
In these cases I indicate dates using BEF followed by the known dates, as below:

1 BIRT
2 DATE BEF 17 MAY 1716
1 CHR
2 DATE 17 MAY 1716

1 DEAT
2 DATE BEF 28 JUL 1764
1 BURI
2 DATE 28 JUL 1764

However, I do not like the additional messages (aged 0 days) and (on the date of death) as a result of the missing dates.
Would it be possible to change the logic behind this? Perhaps dropping the message when using date range/period?

**Comment by ric2016** [comment] 2021-03-02 21:00
This seems to be a duplicate of #3358.

**Comment by fisharebest** [comment] 2021-03-03 14:02
Yes - this is a duplicate.

**Closed by fisharebest** 2021-03-03 14:02 UTC
