### ISSUE TITLE
Level 3 CONT tags not recognised in Level 2 ADDR

### ISSUE THREAD

**Issue by StuartGregory** [fisharebest/webtrees#827] opened 2016-02-05 03:01 UTC
All lines are displayed as if they are on one line.

**Comment by fisharebest** [comment] 2016-02-05 07:23
The formatting was changed a while back to make better use of space.

Most displays have lots of horizontal space, and limited vertical space.

**Comment by StuartGregory** [comment] 2016-02-06 04:46
Thanks Greg for your usual prompt response. Is there a possibility that this position may be reviewed? I would be happy to pose the question on the Forum under General Discussion.

At this stage I simply say that I would like webtrees to accept the entries and the Gedcom formatting I make in the field for the ADDR tag. It is currently a multi-line field and the usual practice for me and most people in my neck of the woods, is to have relatively short, multi-line addresses. Currently webtrees is not accepting Gedcom formatting, but if it reverted to accepting Gedcom formatting, I could enter the address as a long single line if I wanted to (meeting the outcome you outline), or I could enter multi-line format (CONT tags) meeting the outcome I would like.

**Comment by fisharebest** [comment] 2016-02-06 08:18
The default behaviour for HTML/CSS is to treat all whitespace the same as spaces.  So, when we send a multi-line value to the browser, it is the browser that renders it as a single line.  e.g.

**Date:** 1 Jan 1900
**Address:** 1 High Street, Anytown, Somestate
**Place:** Town, State, Country

We could override this using the theme/styling to force line-breaks to be rendered.  e.g.

**Date:** 1 Jan 1900
**Address:** 1 High Street,
Anytown,
Somestate
**Place:** Town, State, Country

But IMHO, the lack of alignment between the first and subsequent lines of the address sucks.  We could force all addresses to start on the next line.  e.g.

**Date:** 1 Jan 1900
**Address:**
1 High Street,
Anytown,
Somestate
**Place:** Town, State, Country

But IMHO, this inconsistency in layout also jars.

**Comment by StuartGregory** [comment] 2016-02-06 10:15
Thanks again Greg for the further explanation. I now understand your dilemma and I happily accept your preferred layout. If asked for a preference I would prefer to have the CONT tag recognised and then I could easily achieve the layout in your last example display. The address is displayed after the PLAC tag and I think that layout is better than having the address all on one line. Just my opinion and as I have said, I will happily accept whatever is best and easiest for you. Your continued development work and support is very much appreciated by me.

**Comment by fisharebest** [comment] 2016-02-21 16:19
I'll close this, since it is working as intended - but am happy to discuss proposals to update the layout/presentation of this data.

**Closed by fisharebest** 2016-02-21 16:19 UTC
