### ISSUE TITLE
Add Media - Folders are missing

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3561] opened 2020-10-19 05:30 UTC
Ver 2.0.9

Browser - Firefox + Edge

This used to work, not certain when it broke.

When adding a media object to a fact there is no option to select which folder on the server it should be placed into.  The "/" is present but the folder names are not populated and there is no option to enter them

Media List does show multiple folders.  [https://behunt.net/ft/tree/hunt/media-list](url)

![Capture](https://user-images.githubusercontent.com/13973937/96404974-39fe1f00-11aa-11eb-801d-e26d94f33992.JPG)

**Comment by fisharebest** [comment] 2020-10-19 08:06
> the folder names are not populated and there is no option to enter them

Type the name of the folder into the box marked "folder"?
There is an autocomplete, which suggests the names of existing folders:

<img width="593" alt="Screenshot 2020-10-19 at 09 04 36" src="https://user-images.githubusercontent.com/2306088/96418121-37231e80-11ea-11eb-9dab-35fd78a101c6.png">

**Comment by eric215** [comment] 2020-10-19 11:40
Thought I had tried that, obviously not.    I'll bring it up for discussion in the forum to get a sense of other's opinions.  To me, having autocomplete works well for place names & source names because you have those sitting right in front of you as you're doing data entry.  If you have media broken out into folders, you don't have a list of the folder names unless you open a new tab and get it via media list.  Lately I have been entering new media much less often so I don't remember exactly how I had it organized.

**Comment by ric2016** [comment] 2020-10-31 11:18
A related issue: The autocomplete does not work as expected if a slash is used as input: searching for "foo/bar" leads to a redirect response, because the slash is used unescaped as part of the url (which ends with "/autocomplete/folder/foo/bar" in this example).
Using '%2F' instead leads to a 404 response (url ends with "/autocomplete/folder/foo%2Fbar").

Should the router handle these cases differently, or do we have to escape slashes (and maybe other characters as well) differently? Sub-folder autocompletion may have to be handled separately in `AutoCompleteFolder.php` in any case.

**Comment by fisharebest** [comment] 2021-01-22 10:56
@eric215 - since this is working, and working as designed, I'll close this.

Feel free to create another issue with suggestions for changes to behaviour (or discuss them on the forum first...)

**Closed by fisharebest** 2021-01-22 10:56 UTC
Labels: bug
