### ISSUE TITLE
2.1.0: Block charts missing on my page

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#4350] opened 2022-04-27 09:15 UTC
When I edit my page, the block charts is missing from the list with available blocks. On the home page the option is available. Could the chart block again be added to my page as well?

**Comment by fisharebest** [comment] 2022-04-28 06:31
Duplicate of #4153

It was removed intentionally, as it does not work on sites with more than one tree.

**Closed by fisharebest** 2022-04-28 06:31 UTC
