### ISSUE TITLE
Main-Menu: dropdown menu and scrollbar

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4386] opened 2022-05-07 11:16 UTC
Similar to #4005 the main-menu has the following problems with the scrollbar of dropdown-menu:

1) The scrollbar overlays the end of the text (see the red marking)
2) Why is the dropdown menu limited in length (= height) when there is still enough space on the screen? If you use a larger part of the screen height, then more often you would not need a scrollbar at all. This would also make it easier to use.

![grafik](https://user-images.githubusercontent.com/28572767/167251620-0ee12480-3e73-405d-a180-a3777d74fa57.png)

**Comment by fisharebest** [comment] 2022-05-08 14:31
This is a duplicate of #4005

Well, half of it is.

You raised two issues in one, which is always difficult to manage.  Please create a separate issue for this.

**Closed by fisharebest** 2022-05-08 14:31 UTC

**Comment by fisharebest** [comment] 2022-05-08 14:41
> Please create a separate issue for this.

Actually, this is a quick fix.

**Comment by ungeahnt** [comment] 2022-05-08 14:46
then no additional isssue?

**Comment by fisharebest** [comment] 2022-05-08 15:28
Correct
