### ISSUE TITLE
Source NOTE first line []() printed on site - wt 2.0.11-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3604] opened 2020-11-24 17:46 UTC
At least for some Note Titles, I see  [] and () when we do not see the full Note.

**Source Note S721 of I39777** in wt version 2
![image](https://user-images.githubusercontent.com/5202996/100120389-91b23900-2e80-11eb-9724-60cd192ddb11.png)

In my pre wt version 2 production site I see the above as expected as
![image](https://user-images.githubusercontent.com/5202996/100120598-c9b97c00-2e80-11eb-9694-9a83e63dea7a.png)
without the [] and ().

The Source Note is
`1 NOTE [Roots archive search](http://digitalastadsarkivet.stockholm.se/Rotemannen2012/Search.aspx)`

Also at least S250 has this issue on the page of I10059.
 
I had similar issues for some **Repository Notes**.

Shared notes have a similar issue.
It seems to me that Individual, Family, Media or any other note URLs do not have this issue, but I am not sure.

**Comment by fisharebest** [comment] 2021-01-22 11:09
This is a duplicate of #2600, which was caused by the fix for #2588

In summary...

The problem is how to generate a "name" for a NOTE.

Previously we used to

1) format the note using markdown, etc.
2) strip HTML
3) take the first line.

However, step 1 will expand links.

So, if your note says

`0 @X1@ NOTE More info about @X123@`

Then webtrees would convert `@X123@` into a name/link to the record.

However, a user had something like this

```
0 @X1@ NOTE Part one (See also @X2@)
0 @X2@ NOTE Part two (See also @X1@)
```

This causes infinite recursion - with no easy means to detect it.

To fix that bug, we now generate the name of the note as simply the first line.

**Closed by fisharebest** 2021-01-22 11:09 UTC
