### ISSUE TITLE
Should show the module sequence number of menues, tabs and sidebars from the database, not reinvent it 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#544] opened 2015-04-02 21:02 UTC
webtrees/admin_module_menus.php
webtrees/admin_module_tabs.php
webtrees/admin_module_sidebar.php

we should show the sequence number from the database, if it exists, and not recalculate it in the module sequence in the page language.

**Comment by fisharebest** [comment] 2015-04-02 21:21
Possible duplicate of #517

**Closed** 2015-04-03 18:55 UTC
