### ISSUE TITLE
2.0.0 relationship between two persons runs in endless loop

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2849] opened 2019-12-09 22:01 UTC
Showing a relationship between two persons always runs in an endless loop. The round circle always runs, but it never finishes to load anything. No error message, but no display of the diagram.

**Comment by t-karcher** [comment] 2019-12-10 08:43
I can't reproduce this - it works for me:
- Simple one: https://familie-dohl.de/index.php?route=%2Ftree%2Ftest%2Frelationships-0-99%2FX1%2FX4
- More complex one: https://familie-dohl.de/index.php?route=%2Ftree%2Fdohl%2Frelationships-0-99%2FI441%2FI88

**Comment by ungeahnt** [comment] 2019-12-10 09:08
On my installation (with 2 trees) I've also the loop when I use 'Find all possible relationships':
https://proavitus.de/dev/index.php?route=%2Fdev%2Ftree%2Froyal92%2Frelationships-0-99%2FI1%2FI133

'Find the closest relationships' is ok:
https://proavitus.de/dev/index.php?route=%2Fdev%2Ftree%2Froyal92%2Frelationships-0-0%2FI1%2FI133

**Comment by fisharebest** [comment] 2019-12-15 19:57
@HonkXL - using the latest code, edit the preferences for the relationship chart module.

Change the "recursion" setting to zero.

Does this make a difference?

**Comment by ungeahnt** [comment] 2019-12-27 09:36
maybe this is helpful (updated today to 2.0.1):
In my case, when I switch to 6 recursions (https://proavitus.de/dev/index.php?route=%2Fdev%2Ftree%2Froyal92%2Frelationships-0-6%2FI1%2FI133)
the relationship chart is always displayed after around 100-110s (with ~20 relationships). Only when the server is a little bit more busy and the process took more time then there is no respone (beside the rotating icon). Even after 10 minutes.
On my server 'max_execution_time' is set to 120. Therefore I think the problem with the endless loop is related to this (or any other) timeout. 
Is it possible to end the recursion before 'max_execution_time' (or other relevant timeouts) with a warning/note and report the calculated data up to that time ?

**Comment by fisharebest** [comment] 2020-04-09 12:17
This issue has been re-opened as #3165 - so closing this one.

**Closed by fisharebest** 2020-04-09 12:17 UTC
