### ISSUE TITLE
2.0.0-beta.3 - Home page block "Charts" shows always "Pedigree"

### ISSUE THREAD

**Issue by TheRealJPS** [fisharebest/webtrees#2483] opened 2019-07-09 21:15 UTC
Even after a change of Chart type to "Descendants", Hourglass chart" or  "Interactiv tree", always "Pedigree" is shown.

**Comment by fisharebest** [comment] 2019-08-18 12:49
I cannot reproduce this problem.

I tried with beta.3 and also the latest code.

Do you still see the problem?

**Comment by TheRealJPS** [comment] 2019-08-18 13:27
jep, I have still the problem (beta3)...

![Zwischenablage01](https://user-images.githubusercontent.com/50000131/63225029-8f1c5a80-c1cc-11e9-8ddf-721329fc6f21.png)
![Zwischenablage02](https://user-images.githubusercontent.com/50000131/63225032-92174b00-c1cc-11e9-8814-dd053d45ccca.png)
![Zwischenablage03](https://user-images.githubusercontent.com/50000131/63225039-9fccd080-c1cc-11e9-86b1-da9fa30c34e6.png)
![Zwischenablage04](https://user-images.githubusercontent.com/50000131/63225040-a3f8ee00-c1cc-11e9-8a70-63d3584bd1ed.png)
![Zwischenablage05](https://user-images.githubusercontent.com/50000131/63225042-ace9bf80-c1cc-11e9-833a-e459ba62ac3a.png)
![Zwischenablage06](https://user-images.githubusercontent.com/50000131/63225043-aeb38300-c1cc-11e9-836f-4f42ade236d1.png)

**Comment by fisharebest** [comment] 2019-08-18 17:05
Can you try the demo site? https://dev.webtrees.net/demo-dev

I think, perhaps, this problem is already fixed in the latest code.

**Comment by TheRealJPS** [comment] 2019-08-18 17:22
The feature works in the demo site very well. Alle selections are displaye.

**Comment by fisharebest** [comment] 2019-08-18 18:01
OK - I think the problem is already fixed.  Wait for the next release.

**Closed by fisharebest** 2019-08-18 18:01 UTC

**Comment by TheRealJPS** [comment] 2019-08-18 19:02
Will do, thanks!

**Comment by TheRealJPS** [comment] 2019-09-04 19:34
This works with 2.0.0-beta.4, thanks!
