### ISSUE TITLE
Individual list has malformed html - missing headers and foooters

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1886] opened 2018-08-31 20:19 UTC
Selecting List/Individuals results in:

![image](https://user-images.githubusercontent.com/5147603/44934070-59166a00-ad20-11e8-8463-0f2b417f0362.png)

**Comment by fisharebest** [comment] 2018-08-31 20:34
Is there an error message hidden in the HTML?

**Comment by makitso** [comment] 2018-08-31 20:48
I looked before but nothing.  Here is the html

`

<div class="d-flex flex-column wt-page-options wt-page-options-individual-list d-print-none">
--
  | <ul class="d-flex flex-wrap wt-initials-list">
  |  
  | <li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=A&amp;ged=peters.ged" class="wt-initial" title="52">A</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=B&amp;ged=peters.ged" class="wt-initial" title="401">B</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=C&amp;ged=peters.ged" class="wt-initial" title="52">C</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=D&amp;ged=peters.ged" class="wt-initial" title="86">D</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=E&amp;ged=peters.ged" class="wt-initial" title="22">E</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=F&amp;ged=peters.ged" class="wt-initial" title="38">F</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=G&amp;ged=peters.ged" class="wt-initial" title="81">G</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=H&amp;ged=peters.ged" class="wt-initial" title="161">H</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=I&amp;ged=peters.ged" class="wt-initial" title="6">I</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=J&amp;ged=peters.ged" class="wt-initial" title="36">J</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=K&amp;ged=peters.ged" class="wt-initial" title="113">K</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=L&amp;ged=peters.ged" class="wt-initial" title="58">L</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=M&amp;ged=peters.ged" class="wt-initial" title="197">M</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=N&amp;ged=peters.ged" class="wt-initial" title="16">N</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=O&amp;ged=peters.ged" class="wt-initial" title="39">O</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=P&amp;ged=peters.ged" class="wt-initial active" title="299">P</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=Q&amp;ged=peters.ged" class="wt-initial" title="4">Q</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=R&amp;ged=peters.ged" class="wt-initial" title="55">R</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=S&amp;ged=peters.ged" class="wt-initial" title="187">S</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=T&amp;ged=peters.ged" class="wt-initial" title="31">T</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=U&amp;ged=peters.ged" class="wt-initial" title="6">U</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=V&amp;ged=peters.ged" class="wt-initial" title="109">V</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=W&amp;ged=peters.ged" class="wt-initial" title="84">W</a></li><li class="wt-initials-list-item"><span class="wt-initial text-muted">X</span></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=Y&amp;ged=peters.ged" class="wt-initial" title="3">Y</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=Z&amp;ged=peters.ged" class="wt-initial" title="4">Z</a></li><li class="wt-initials-list-item"><a href="http://localhost/index.php?route=individual-list&amp;alpha=%40&amp;ged=peters.ged" class="wt-initial" title="17">…</a></li><li class="wt-initials-list-item"><a class="wt-initial" href="http://localhost/index.php?route=individual-list&amp;show_all=yes&amp;ged=peters.ged&amp;surname=Peters">All</a></li></ul><p><a href="http://localhost/index.php?route=individual-list&amp;show=indi&amp;show_marnm=yes&amp;ged=peters.ged&amp;surname=Peters">Include individuals with “<span dir="auto">PETERS</span>” as a married name</a></p>        </div>
  | <div class="wt-page-content">
  | <h2 class="wt-page-title">Individuals with surname <span dir="auto">PETERS</span></h2><ul class="d-flex flex-wrap justify-content-center wt-initials-list"><li class="wt-initials-list-item">

`

**Comment by magicsunday** [comment] 2018-09-05 11:27
Seems to be fixed in current master.

**Comment by makitso** [comment] 2018-09-05 21:08
So, was this fixed?  I am confused since the problem still exists after today's github update

**Comment by fisharebest** [comment] 2018-09-05 21:18
I couldn't reproduce it, and I found a code change that looks like it should have fixed it.

**Comment by makitso** [comment] 2018-09-05 21:31
Here is how I get this error:   I have 272 people in my gedcom with the name of Peters.  Even though I have no default individual set for the peters gedcom, most charts start with a specific individual and the list function has a url below.
http://localhost/index.php?route=individual-list&ged=peters&surname=Peters

Now, if I add a default individual say someone with the last name of Amy Bradley, then the Charts/Individuals work correctly and produces a url of:
http://localhost/index.php?route=individual-list&ged=peters&surname=Bradley

However, if I delete the default individual it still remembers the Bradley name and all charts begin with Amy Bradley.  Looks like the removal of a default individual is not clearing the database value.

**Comment by fisharebest** [comment] 2018-09-06 20:04
>  Looks like the removal of a default individual is not clearing the database value.

Strange.  We only store the XREF of the individual in the database.  The surname 'Bradley' must be coming from somewhere....

**Closed** 2018-09-06 20:08 UTC
