### ISSUE TITLE
Webtrees crashs if module could not be loaded because of an fatal error

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#455] opened 2015-02-26 16:55 UTC
I currently used the module *wooc_singlepage_pedigree* with the latest dev version of webtrees. Due the massive changes in the class structure the module throws an fatal error while trying to load WT_Module which does not longer exists.

There is no way to disable this plugin using the admin tools. Its only possible to manipulate the database entry in table *wt_module*. 

But if disabled the admin page *admin_modules.php* fails with an fatal error due *Module::getInstalledModules('disabled');*

I think there should be a third state "compatible" or something to fully disable plugins/modules which are not compatible with webtrees because if internal changes. 

* Maybe every module should provide some kind of versioninfo file which contains the latest working version of webtrees the module was tested with? 
* Or simply disable all not default webtrees modules and inform the user about it? 
* Or maybe a little extra script the test module loading (should be possible with AJAX I think)?

**Comment by fisharebest** [comment] 2015-02-26 16:59
This is related to #452 and #413.

**Comment by fisharebest** [comment] 2015-03-02 18:35
I have just submitted some changes to the way we load modules.

We now have a `try {} catch {}` block to catch these errors,

Can you tell me if the latest code fixes the problem for you.

**Comment by JustCarmen** [comment] 2015-03-02 22:35
Greg, since I pulled the latest changes which includes the new module api I can't get into the admin module list anymore. I keep getting the following error:

Fatal error: Call to a member function getName() on a non-object in C:\xampp\htdocs\webtrees_build\app\Module.php on line 372

Before I merged these changes I disabled all custom modules. But that didn't help. Then I removed all entries from the database and at last I removed all custom modules out of the module directory, because I wasn't sure this error wasn't caused by one of my modules. But I am still getting this error.

**Comment by JustCarmen** [comment] 2015-03-02 22:40
Sorry it was caused by a custom module. I forgot one: custom_js which isn't mine. Thats why I overlooked this one in the first place. But only by removing all custom modules I can go into the admin module list.

**Comment by fisharebest** [comment] 2015-03-02 22:42
I had assumed that since line 372 is in a `try {} catch {} block`, the error would be caught correctly.
Let me take another look

**Comment by fisharebest** [comment] 2015-03-02 22:48
Try the latest code.

**Closed** 2015-03-02 22:48 UTC

**Comment by JustCarmen** [comment] 2015-03-02 23:09
I moved all custom modules back to the module folder to test this out and it is working. I am in now. But the custom modules don't appear in the list anymore and I think this is correct behavior, since they are not yet updated, am I right?

**Comment by vytux-com** [comment] 2015-03-03 04:35
I just tried the latest version (without disabling the custom modules first) and I get this error:

#0 /app/Module.php:243 ErrorException("Undefined index: vytux_gallery3") #1 /app/Module.php:267 getActiveModulesByComponent([Tree], 'block', 0) #2 /index.php:46 getActiveBlocks([Tree])

Should those changes have made it possible for me to enter the site without updated modules and is there a guide of what the new API changes mean to custom modules?

**Comment by JustCarmen** [comment] 2015-03-03 05:44
@Vytux: to get your modules up and running again it only takes a few modifcations. I will take the Fancy Treeview Module as example to explain:
 
1. Change the classname to FancyTreeviewModule
2. At the end of the class, after the last } enter the line: return new FancyTreeviewModule
3. In the constructor change this line: parent::__construct() to parent::__construct('fancy_treeview');
    between the () you need to enter the directory name of the module.

The first step is not necessary but it is consistent with the naming conventions of the core modules. The name in the second step must be equal to the class name from the first step.

**Comment by vytux-com** [comment] 2015-03-03 07:06
@JustCarmen Thank you. That does indeed work I was a little confused by the app\modules folder though it meant that we need to convert all custom modules into single page versions.
