### ISSUE TITLE
Large Blob on Modules Panel

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3280] opened 2020-05-20 17:51 UTC
I just set up a fresh copy of v2.0.4 and I'm seeing this:

![screen3](https://user-images.githubusercontent.com/1371835/82479925-0acf6e80-9aa1-11ea-9a4e-e648b2292336.png)

**Comment by fisharebest** [comment] 2020-05-20 18:46
Duplicate of #3265

**Closed by fisharebest** 2020-05-20 18:46 UTC
