### ISSUE TITLE
Adding a person's nickname

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2473] opened 2019-06-26 13:45 UTC
Adding a person's nickname to the family tree, the change has been confirmed, but the nickname is still empty. New addition error, editing is normal.
wt beta3

**Comment by fisharebest** [comment] 2019-08-18 13:00
I guess I saw the problem once.

But I cannot reproduce it now.

**Comment by kexuebin** [comment] 2019-08-18 13:16
New (newly added) person's nickname, the change has been confirmed, but the nickname is empty. Editor's nickname is normal. I just tested it and the problem remains.

**Comment by fisharebest** [comment] 2019-08-18 17:06
Can you try this on the demo site?

https://dev.webtrees.net/demo-dev

I think, perhaps, this problem is already fixed in the latest code.

**Closed** 2019-08-26 14:07 UTC
Labels: bug
