### ISSUE TITLE
Cannot accept changes in HEAD

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3269] opened 2020-05-19 11:31 UTC
After updating to 2.0.4 I can click again at the tree management control page on the indicated 2 submitters of a tree (with the name "alecia"). No error message anymore, this problem is solved. Thank you! Then I deleted one of the two SUBM records. This is ok. 

2020-05-19 13:04:03 | edit | Delete: SUBM X221 | 87.173.222.178 | hermann | alecia
-- | -- | -- | -- | -- | --

Now I searched for HEAD, this opens the HEAD record. I can see that there are still links to two SUBM records, one is ok, the second one links to the just deleted record @X221@. Maybe this is bug #1. Now I deleted this link in HEAD. But when I try to accept this change, it is not possible (illegal GEDCOM record) (bug #2). What is irritating for me: the first log entry contains " | hermann | alecia", the error message contains at the end "| hermann | \<none>". 

2020-05-19 13:06:42 | error | Ungültiger GEDCOM-Datensatz&lt;pre&gt;0 HEAD 1 SOUR webtrees 2 NAME webtrees 2 VERS 1.7.16 1 DEST DISKETTE 1 DATE 16 JAN 2020 2 TIME 19:43:22 1 GEDC 2 VERS 5.5.1 2 FORM Lineage-Linked 1 CHAR UTF-8 1 FILE alecia 1 SUBM @SUB1@ &lt;/pre&gt; …/app/Functions/FunctionsImport.php:1078 #0 …/app/Services/PendingChangesService.php(87): Fisharebest\Webtrees\Functions\FunctionsImport::updateRecord(&#039;0 HEAD\r\n1 SOUR ...&#039;, Object(Fisharebest\Webtrees\Tree), false) #1 …/app/Http/RequestHandlers/PendingChangesAcceptRecord.php(72): Fisharebest\Webtrees\Services\PendingChangesService-&gt;acceptRecord(Object(Fisharebest\Webtrees\Header)) #2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\PendingChangesAcceptRecord-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#4 …/modules_v4/faces/src/Modules/FacesModule.php(82): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#6 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(221): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #8 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #10 …/app/Http/Middleware/AuthModerator.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthModerator-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #15 …/app/Http/Middleware/Router.php(133): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #22 .... | 87.173.222.178 | hermann | \<none>
-- | -- | -- | -- | -- | --

**Comment by fisharebest** [comment] 2020-05-19 22:51
> But when I try to accept this change, it is not possible (illegal GEDCOM record) (bug #2).

I cannot reproduce this.

I add a SUBM link in the header.
I accept the change.
I delete the SUBM link in the header.
I accept the change.

**Comment by hartenthaler** [comment] 2020-05-19 23:06
You are right. I just tried it again with two other of the six trees. It is working perfectly there. It does not work with two other trees. So I have to check what is special with them.

**Comment by fisharebest** [comment] 2021-02-27 09:46
There have been lots of updates to the handling of HEAD/SUBM records since this issue was opened.

I guess the problem is now fixed.

**Closed by fisharebest** 2021-02-27 09:46 UTC
Labels: cannot reproduce
