### ISSUE TITLE
Change Color Coding - Geographic Data

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3425] opened 2020-07-22 18:52 UTC
Enhancement Request

On the **Control Panel  Geographic Data** page, please select a more "neutral" icon color such as blue, purple, tan etc, instead of red for places that have no child entries and no errors.

![pic_one](https://user-images.githubusercontent.com/13973937/88216350-fc313f00-cc2a-11ea-9c7f-cfe0d5033706.JPG)

**Comment by fisharebest** [comment] 2020-07-23 08:07
The problem is not the choice of colour.

The problem is that we are using colour (and only colour) to convey information.

This means it is not accessible to users who are colour-blind or who use high-contrast mode.

We need a different (or additional) way of showing this information.

**Comment by fisharebest** [comment] 2020-07-23 16:37
Fixed in 94e359174878c0eebf102ead543b66cb58a757d0

**Closed by fisharebest** 2020-07-23 16:37 UTC
