### ISSUE TITLE
F.A.B theme: Bug in Upcoming events and On this day

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3262] opened 2020-05-18 16:34 UTC
Part of Bell icon (?) displayed in the blocks Upcoming events and On this day when set to table style.
![mypage](https://user-images.githubusercontent.com/55854079/82237562-236f4580-9936-11ea-8c04-5f5ae33328bd.jpg)

**Comment by fisharebest** [comment] 2020-05-18 16:38
I don't see this on the demo server or on my own site.

Can you post a URL where I can see this?

**Comment by HRN65** [comment] 2020-05-18 16:39
https://visitusinmaputo.com/webtree/tree/29082010.GED

**Comment by fisharebest** [comment] 2020-05-18 16:42
Works for me.  This is what I see on your site:

Restart browser/clear cache/???

![Screenshot 2020-05-18 at 17 40 43](https://user-images.githubusercontent.com/2306088/82238250-e3589480-992e-11ea-9070-62050e48570b.png)

**Comment by fisharebest** [comment] 2020-05-18 16:44
OK - I got it.

The bug appears in Chrome, but not in Firefox...

**Comment by HRN65** [comment] 2020-05-18 16:52
Bug also present in Control panel / All modules. Looks fine in Edge
![controlpanel](https://user-images.githubusercontent.com/55854079/82239139-9bd70600-9938-11ea-98be-531b7cf22909.jpg)

**Comment by Gunnar-GO** [comment] 2020-05-18 17:46
I wanted to post the same bug after upgrading to 2.0.4.

Seems to be an error handling svg in text.
This brings me to another question why an embedded SVG is used while other symbols are embedded in CSS. Maybe the difference between the topics?

Aren't there some matching fonts like Font Awesome? Since the symbols seem to be the SVG variants from there, maybe we could use FA directly.

**Comment by fisharebest** [comment] 2020-05-18 22:57
> maybe we could use FA directly.

We *are* using font-awesome directly.

It has two ways to use it - CSS fonts and SVG.  SVG is the recommended option.

#3265 is a duplicate of this - but I will close this issue and keep the other one because I liked the (original) title of it "graphic violence" ;-)

**Closed by fisharebest** 2020-05-18 22:57 UTC
Labels: bug
