### ISSUE TITLE
Add from clipboard & Fact or Event don't shrink to fit in browser (v2.0.10)

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#3583] opened 2020-11-03 14:16 UTC
![Screenshot 2020-11-03 140127](https://user-images.githubusercontent.com/5928173/97994774-92a1fe80-1ddd-11eb-9b41-bcd3bb0da144.png)

The "Add from Clipboard" & "Fact or Event" input windows don't shrink to the size of the browser tab when the tab is narrow (not maximised), thus hiding the "add" boxes. The user has to maximise the tab in order to see the "Add". There is no left-right scroll feature.

Incidentally, census tables don't shrink either - though that would entail making the font used in the table smaller. That might be acceptable, though it might need to be an option.

**Comment by ddrury** [comment] 2020-11-05 13:16
See https://github.com/fisharebest/webtrees/issues/1427

**Comment by fisharebest** [comment] 2020-11-12 12:42
Duplicate of existing issue.

FYI, I am struggling to find a fix for this.

The "official" solution is to use responsive-tables - https://getbootstrap.com/docs/4.5/content/tables/#always-responsive

But this does not work here...

**Closed by fisharebest** 2020-11-12 12:42 UTC
