### ISSUE TITLE
Admin functions give blank screen after update 5b670e3

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1723] opened 2018-05-12 16:50 UTC
Several Admin functions no longer work - blank screen: Website logs, Wesite preferences, Sending email, Sign-in and registration, Languages and Tracking and analytics.

[Sat May 12 09:53:36.066892 2018] [php7:error] [pid 25037] [client ::1:41604] PHP Fatal error:  Uncaught Error: Call to undefined method Fisharebest\\Webtrees\\Theme\\AdministrationTheme::sendHeaders() in /var/www/app/Controller/PageController.php:119\nStack trace:\n#0 /var/www/admin_site_logs.php(185): Fisharebest\\Webtrees\\Controller\\PageController->pageHeader()\n#1 {main}\n  thrown in /var/www/app/Controller/PageController.php on line 119, referer: http://localhost/index.php?route=admin-control-panel
[Sat May 12 09:53:39.396481 2018] [php7:error] [pid 3439] [client ::1:41608] PHP Fatal error:  Uncaught Error: Call to undefined method Fisharebest\\Webtrees\\Theme\\AdministrationTheme::sendHeaders() in /var/www/app/Controller/PageController.php:119\nStack trace:\n#0 /var/www/admin_site_logs.php(185): Fisharebest\\Webtrees\\Controller\\PageController->pageHeader()\n#1 {main}\n  thrown in /var/www/app/Controller/PageController.php on line 119

**Comment by fisharebest** [comment] 2018-05-12 16:56
I got a bit ahead of myself with some updates, and removed some old code that was still used.

Duplicate of #1721

**Closed by fisharebest** 2018-05-12 16:56 UTC
