### ISSUE TITLE
Initial display of toggleable events broken - 2.0.0

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2068] opened 2018-12-27 10:57 UTC
On the Facts and events tab, if "Events of close relatives" is checked, the respective events are not actually shown when the page is initially loaded (or reloaded). 
(When toggling the checkbox, the display of events switches between shown and hidden as expected, although the checkbox state may get mixed up as a consequence of the bug)

This is reproducible in the current demo showcase, e.g. [here:](https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=i202)

**Comment by fisharebest** [comment] 2018-12-31 17:58
Duplicate of #1711 which has just been fixed.

**Closed by fisharebest** 2018-12-31 17:58 UTC
