### ISSUE TITLE
Name error in adding daughter to Mexican family

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4023] opened 2021-09-01 21:57 UTC
I had a Mexican FAM with parents' given names unknown.  Father … Arellano; mother … Contreras.

I learned the names of some of the children, so I went to control panel and changed the default surname tradition to Spanish.

Then I went to the FAM and clicked "add daughter."  Put Pilar in the given name field and went to the INDI.  Pilar was not shown, only the surnames without an ellipsis in front.  Selected raw GEDCOM and found this:
```
1 NAME /Arellano/ /Contreras/
2 GIVN Pilar
2 SURN Arellano,Contreras
```
version 2.0.16 with Vesta modules, including "classic"

**Comment by fisharebest** [comment] 2021-09-04 19:07
> I had a Mexican FAM with parents' given names unknown. Father … Arellano; mother … Contreras.

Does this mean `/.../ /Arellano/` or `... /Arellano/`?

Perhaps provide a test GEDCOM file?

**Comment by WGroleau** [comment] 2021-09-04 20:51
Attached file 4023.ged contains the entire FAM as it was before seeing the issue.

I put FAC in the search and then clicked on "family with parents."  On that page, I clicked "add a daughter," put "Pilar" in the 'given name' field and clicked "go to new individual."  Did some more edits there, then went back to the FAM page, did it again with a brother, and again with another sister.  

I just went to the FAM again and clicked "Add son."  Add_son.jpg shows what the pop-up looks like.  I put "test" in the "given names" and "go to new indi…"  test_display and test_gedcom shows the result.

I was not aware before that web trees puts the surnames as two separately delimited items.  The GEDCOM 5.5.1 draft does not mention Spanish traditions (AFAIK) but page 54 has
William Lee /Mac Parry/ (both parts (Mac and Parry) are surname parts
which is the way I have some to understand Spanish thought.  I can change my Mexican INDIs to the /xxx/ /yyy/ style, but I think both styles should be supported.

OR add a note above the surname field on the add/edit pop-ups saying what tradition is selected and what format should be entered into the field for that tradition.

[4023.ged.txt](https://github.com/fisharebest/webtrees/files/7110500/4023.ged.txt)
![test_gedcom](https://user-images.githubusercontent.com/5910274/132107530-2a90e13a-5590-4575-899f-4710c97fd2b6.jpg)
![test_display](https://user-images.githubusercontent.com/5910274/132107533-52180211-3a1f-4a7b-8fb6-54f29577241f.jpg)
![Add_son](https://user-images.githubusercontent.com/5910274/132107534-48ed406d-aa40-4f3b-a293-407137ca6b09.jpg)

**Comment by fisharebest** [comment] 2021-09-05 12:09
OK - the problem is that for Spanish/Portuguese names, webtrees puts slashes round each surname.

* `given /surname1 surname2/` is a name with one surname (consisting of 2 words)
* `given /surname1/ /surname2/` is a name with two surnames
* `given /surname1/ y /surname2/` is a name with two surnames (separated by a particle)
* `given /surname1/ //` is a name with two surnames - one of which is unknown.

The surname tradition logic assumes you are using this structure.

So, you would need to change `1 NAME /Arellano …/` to `1 NAME /Arellano/ //`

**Comment by WGroleau** [comment] 2021-09-05 22:14
So, if we can't handle the way I (and I presume other Spanish speakers) think of it, than we should add text to the form that can help others to avoid the formatting I used.

**Comment by fisharebest** [comment] 2021-09-07 08:11
> we should add text to the form that can help others to avoid the formatting I used.

This is mentioned in the help text.  (Click the help icon at the end of the name field.)

<img width="825" alt="Screenshot 2021-09-07 at 09 10 23" src="https://user-images.githubusercontent.com/2306088/132308877-b9109903-84f9-4396-9755-a666e613ce3e.png">

**Comment by fisharebest** [comment] 2021-09-09 09:42
Closing, as I think this is working as designed.

**Closed by fisharebest** 2021-09-09 09:42 UTC
