### ISSUE TITLE
Elements overlapping in Safari browser when data has more than one line

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#4414] opened 2022-05-18 19:49 UTC
I created a residence entry on dev.webtrees.net with more than one line in the address field like:
somwhere
there
1234

This results in overlapping objects - see screenshot.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/16715040/169143323-d2bdd2e4-a4b2-42bb-9228-cc187c17e2e7.png">

I looks a bit better when disabling display: inline-block!important in the css - see this screenshot:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/16715040/169143614-ad9f3763-e0d5-4753-9f31-2dbd54c03368.png">

Problem exists in latest Safari on MacOS

**Comment by fisharebest** [comment] 2022-05-18 19:51
Duplicate of #4353

**Closed by fisharebest** 2022-05-18 19:51 UTC
