### ISSUE TITLE
Page "User administration" : blank pop-up on email link

### ISSUE THREAD

**Issue by SodanWT** [fisharebest/webtrees#786] opened 2015-12-18 00:06 UTC
Firefox 42/Linux

On page "User administration" after clicking on a user e-mail, there is just a blank pop-up.
Seems related to the "span" tag in the javascript link, as when removing it the pop-up loads properly.
```html
<a href="#" onclick="return message('<span dir=&quot;auto&quot;>test</span>', '', '');">email@example.com</a>
```

**Comment by fisharebest** [comment] 2015-12-18 00:18
Duplicate of #734 and already fixed ;-)

**Closed by fisharebest** 2015-12-18 00:18 UTC

**Comment by SodanWT** [comment] 2015-12-18 00:33
I searched issues with "mail" keyword, not "email"...
Sorry.

**Comment by fisharebest** [comment] 2015-12-18 00:35
No problem!
