### ISSUE TITLE
GEDCOM Import

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#2946] opened 2020-01-06 16:22 UTC
After selecting prior generated GEDCOM for import to set back

the page returns to administration page and shows error:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-M1' for key 'PRIMARY' (SQL: insert into `wt_media` (`m_id`, `m_file`, `m_gedcom`) values (M1, 1, 0 @M1@ OBJE 1 FILE _GENERICFILENAME_.jpg 2 FORM jpeg 3 TYPE photo 1 CHAN 2 DATE 04 JAN 2020 3 TIME 03:39:47 2 _WT_USER Gunnar))`

the error is forced if _keep mediaobjects_ is selected.

**Comment by fisharebest** [comment] 2020-01-09 14:24
This is to be expected.

The options "keep media objects" is only to be used when your GEDCOM file does not contain any media objects.

I guess that we should ignore media objects in the GEDCOM file when we use this option.

**Comment by fisharebest** [comment] 2021-05-25 08:28
Duplicate of #1714

**Closed by fisharebest** 2021-05-25 08:28 UTC
