### ISSUE TITLE
2.0.6 - Markdown syntax visible in List > Shared notes > Title

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3402] opened 2020-07-07 18:30 UTC
When I use markdown syntax (like `## `or `**`) in the title of Shared notes, this syntax is visible in `List > Shared notes > Title`.

Is it possible to remove this syntax characters from the Shared notes list?

**Comment by fisharebest** [comment] 2020-07-07 19:00
This is a duplicate of #2600

The problem is that we convert XREFs in notes into links.

To calculate the links, we must generate the names of other objects.

Which can include other notes - which causes an infinite loop.

e.g.

```
0 @N1@ NOTE
1 CONT See @N2@
0 @N2@ NOTE
1 CONT See @N1@
```

**Closed by fisharebest** 2020-07-07 19:00 UTC

**Comment by TheDutchJewel** [comment] 2020-07-08 07:25
Is it possible to make an exception for markdown syntaxes for the shared note XREFs?
So that XREFs starting with '`## `', '`### `' or '`#### `', or between '`*`' or '`**`' are not allowed?

**Comment by fisharebest** [comment] 2020-07-08 07:37
The bigger question is

What is the "name" of a shared note object?

**Comment by TheDutchJewel** [comment] 2020-07-08 08:04
>What is the "name" of a shared note object?

Anything between `0 @Note XREF@` and `1 CONT`?
