### ISSUE TITLE
Nickname should be inbetween first & surname

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#1528] opened 2017-12-05 16:55 UTC
Current beta shows nicknames after the full name instead of inbetween first names and the surname.
Also see  forum discussion https://www.webtrees.net/index.php/en/forum/3-help-for-beta-and-github-versions/32366-add-adoiption-to-beta#66029

**Comment by fisharebest** [comment] 2017-12-05 17:11
I think this is a duplicate of #1401

**Closed by fisharebest** 2017-12-05 17:11 UTC
