### ISSUE TITLE
2.0-Unable to display page when there are pending changes

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2282] opened 2019-02-28 02:43 UTC
When I add a pending change block on the home page, if there is a pending change record that is not accepted or rejected, the home page will not be displayed and a http 500 error will occur.

![http500](https://user-images.githubusercontent.com/26761596/53537581-67193c00-3b45-11e9-9796-2cf4b71e54aa.gif)

**Comment by fisharebest** [comment] 2019-02-28 07:02
Are there error messages in the webtrees error log?

Are there error messages in the webservererror log?

**Comment by xmlf** [comment] 2019-02-28 07:21
> Are there error messages in the webtrees error log?
> 
> Are there error messages in the webservererror log?

The webserver log only has an "HTTP/2.0 500 0" error.
No error log is displayed in the control panel log.

**Comment by magicsunday** [comment] 2019-02-28 11:19
The only bug I see is, that the list of the "pending changes" module appends every new change to an existing list. If I accept a change (or all) the list is not cleared. Any new change is append to the previous list.

**Comment by xmlf** [comment] 2019-03-01 00:46
> Are there error messages in the webtrees error log?
> 
> Are there error messages in the webservererror log?
Sorry, my server has turned off php error reporting by default.
After I turn it on, the error message is as follows:

`Fatal error: Uncaught Error: Call to a member function canShow() on null in /home/wwwroot/jiazu/jiazu/app/Module/ReviewChangesModule.php:153 Stack trace: #0 /home/wwwroot/jiazu/jiazu/resources/views/tree-page-block.phtml(5): Fisharebest\Webtrees\Module\ReviewChangesModule->getBlock(Object(Fisharebest\Webtrees\Tree), 59, 'gedcom') #1 /home/wwwroot/jiazu/jiazu/app/View.php(143): include('/home/wwwroot/j...') #2 /home/wwwroot/jiazu/jiazu/app/View.php(187): Fisharebest\Webtrees\View->render() #3 /home/wwwroot/jiazu/jiazu/app/Helpers/functions.php(108): Fisharebest\Webtrees\View::make('tree-page-block', Array) #4 /home/wwwroot/jiazu/jiazu/resources/views/tree-page.phtml(11): view('tree-page-block', Array) #5 /home/wwwroot/jiazu/jiazu/app/View.php(143): include('/home/wwwroot/j...') #6 /home/wwwroot/jiazu/jiazu/app/View.php(187): Fisharebest\Webtrees\View->render() #7 /home/wwwroot/jiazu/jiazu/app/Helpers/functions.php(108): Fisharebest\Webtrees\View::make('tree-page', Array) #8 /home/wwwroot/jiazu/jiazu/app/Http/Controllers/Ab in /home/wwwroot/jiazu/jiazu/app/Module/ReviewChangesModule.php on line 153`

**Comment by fisharebest** [comment] 2019-03-01 09:32
Thanks.  Duplicate of #2285

**Closed by fisharebest** 2019-03-01 09:32 UTC
