### ISSUE TITLE
PHP TypeError on updateFact()

### ISSUE THREAD

**Issue by havepowilltravel** [fisharebest/webtrees#1910] opened 2018-09-16 14:34 UTC
Webtrees 2.0.0-apha1

When editing an individual's name (such as adding a middle name), a blank screen is displayed after clicking "save."  Yes, blank.  No menus, nothing except the browser's widow dressing.

The Apache log shows this error:

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Fisharebest\\Webtrees\\Http\\Controllers\\EditGedcomRecordController::updateFact() must be an instance of Fisharebest\\Webtrees\\Tree, none given, called in /srv/www/htdocs/webtree/app/Http/Controllers/EditIndividualController.php on line 622 and defined in /srv/www/htdocs/webtree/app/Http/Controllers/EditGedcomRecordController.php:390\nStack trace:\n#0 /srv/www/htdocs/webtree/app/Http/Controllers/EditIndividualController.php(622): Fisharebest\\Webtrees\\Http\\Controllers\\EditGedcomRecordController->updateFact(Object(Symfony\\Component\\HttpFoundation\\Request))\n#1 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\EditIndividualController->editNameAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /srv/www/htdocs/webtree/app/Resolver.php(83): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\EditIndividualController), Object(Symfony\\Component\\HttpFoundation\\Request))\n#3 /srv/www/htdocs/webtree/index.php(321): Fisharebest\\Webtrees\\Resolver->dispa in /srv/www/htdocs/webtree/app/Http/Controllers/EditGedcomRecordController.php on line 390, referer: http://jeans.silutions.net/index.php?route=edit-name&xref=X14&fact_id=ffad7fa02c68d5661925ed8751f094dc&ged=tree1

Kind of annoying, actually.

**Comment by fisharebest** [comment] 2018-09-16 15:10
This is a duplicate of #1834 which has already been fixed.

You should upgrade to 2.0.0-alpha.2

**Closed by fisharebest** 2018-09-16 15:10 UTC
