### ISSUE TITLE
Favicon wrong path

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2070] opened 2018-12-27 14:12 UTC
Trying to retrieve the favicon from the selected theme folder whereas they are located in themes\_common\css-2.0.0

**Comment by fisharebest** [comment] 2019-01-01 12:36
This is a duplicate of #1780 

I would like all public resources (such as icons, css, etc.) to be moved to the `/public/` folder.

However, themes and modules currently live in their own (non public) folders.

Most likely, we'll add the theme CSS files and icons to the build script (`npm run production`), which will minify them and copy them to the public folder.

**Closed** 2019-01-01 12:36 UTC
