### ISSUE TITLE
show related persons of an event

### ISSUE THREAD

**Issue by Joppla** [fisharebest/webtrees#1267] opened 2017-07-01 14:52 UTC
I found out that I I add related persons to an event that the event is not shown in the events of added person.

For Example:
In the marriage of Mr A en Mrs B I added as witnesses Mr C, Mr D, Mrs E.
The marriage is only shown in the eventlist of Mr C  but not in the list of Mr D and Mrs E.

**Comment by fisharebest** [comment] 2017-07-01 15:08
Duplicate of #1192

**Closed by fisharebest** 2017-07-01 15:08 UTC
