### ISSUE TITLE
Dev 2.0 - Colors and clouds Tree dropdown displayed incorrectly

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1747] opened 2018-05-26 20:44 UTC
I am not sure when this happened but the dev 2.0 system now displays the main tree downdown incorrectly.

How it was displayed:
![image](https://user-images.githubusercontent.com/5147603/40580030-c599f818-60ea-11e8-9fec-06cb923162e6.png)

How is is now:
![image](https://user-images.githubusercontent.com/5147603/40580036-e9120916-60ea-11e8-9ea8-8aab6a19a929.png)

**Comment by melizaa** [comment] 2018-05-28 04:52
We have the same issue for almost all the dropdown menues.

**Comment by fisharebest** [comment] 2018-05-31 14:45
I think this is a duplicate of #1748

**Closed by fisharebest** 2018-05-31 14:45 UTC
