### ISSUE TITLE
large icons on wt_2.07?

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3505] opened 2020-09-15 12:38 UTC
As I started working at my trees again, I noticed that wt shows some very large icons. 

This was on Mircrosoft Edge (version 85.0.564.51). I didn't test any other browsers, but didn't notice this behaviour before. So this is a specific problem in combination with the newest version of ME?

![wt](https://user-images.githubusercontent.com/45886938/93210916-c60ec800-f760-11ea-85cb-f53d55e753a5.png)

**Comment by fisharebest** [comment] 2020-09-15 13:54
This looks like a duplicate of #3265 which is already fixed.

Are you definitely using 2.0.7?

Have you cleared your browser's cache?

**Comment by Lars1963** [comment] 2020-09-15 15:22
@fisharebest yes and yes

I installed wt for 2 weeks on a new server. Can't remember to have seen that behaviour then.

I checked just now on my android-tablet (with chrome) . At first everything was ok. BUT after I cleared its browser cache, there the large icons are also seen. 🥴

**Comment by fisharebest** [comment] 2020-09-16 06:05
Are the large icons only in the admin pages - or do you see them on the genealogy pages?

**Comment by Lars1963** [comment] 2020-09-16 11:42
Hello Greg, I see them on all pages.

**Comment by fisharebest** [comment] 2020-09-16 16:21
Can you post the URL of a page where I can see it?

**Comment by Lars1963** [comment] 2020-09-16 16:39
@fisharebest  https://genealogie.ravenzwaaij.eu/tree/ravenzwaaij

This is a screenshot of the control panel at 75% zoom in the browser:

![wt_2](https://user-images.githubusercontent.com/45886938/93366788-e7001780-f84b-11ea-834e-52244354c2a7.png)

**Comment by fisharebest** [comment] 2020-09-17 06:16
I need to see the actual website, so I can examine the HTML, CSS, etc.

You said you see it on non-admin pages.  Can you send me the URL of a public page where I can see it?

**Comment by fisharebest** [comment] 2020-09-17 14:59
> You can allready see it on the landing-page (see link above).

Sorry - I missed that.

I see you have several modules installed, including "vesta classic look and feel".

Can you temporarily disable **all** your custom modules, and see if the problem is still there?

**Comment by Lars1963** [comment] 2020-09-17 15:17
OK. Disabling the Vesta-Modules solved the problem partly. On the landing page everything seems to be okay now. On subpages the situtuation improved, but not solved. The same on the admin-pages.

And before you ask, I cleared my browser's cache😁

cc @ric2016

**Comment by ric2016** [comment] 2020-09-17 15:46
> Disabling the Vesta-Modules solved the problem partly.

If only partly, it's likely a coincidental effect. I'll check my module's css, but I don't think this is caused by the custom module.
Of course it's still better to keep them disabled in order to debug further.

**Comment by Lars1963** [comment] 2020-09-17 16:01
@ric2016 You seem to be right.

@fisharebest If I use the minimal or the f.a.b. theme the problem on the landing page is seen there also. All other standard-themes don't show that effect.

**Comment by fisharebest** [comment] 2020-09-19 14:18
Your site is setting a content-security policy header:

`content-security-policy | default-src  'none'; base-uri 'none'; manifest-src 'self'; script-src 'self';  style-src 'self'; img-src 'self' data: blob:; font-src 'self' data:;  connect-src 'self'; media-src 'self'; frame-src 'self'; frame-ancestors  'self'; worker-src 'self' blob:; form-action 'self';`

The browser's error console shows lots of the following errors:

```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("style-src").
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").
```

Your security policy is preventing the styles from being applied.

Remove or relax the security policy.

**Closed** 2020-09-19 14:19 UTC

**Comment by Lars1963** [comment] 2020-09-19 19:29
@fisharebest Thanks for your help and debugging. I've relaxed my settings a bit and still getting a grade **A+** on the Moz://a HTTP Observatory, but sadly 20 points down because of:
_`Your current CSP policy allows the use of 'unsafe-inline' inside of style-src. Moving style attributes into external stylesheets not only makes you safer, but also makes your code easier to maintain`_


On debugging the CSP-Rules the error console remains to show this
**`DevTools failed to load SourceMap: Could not load content for https://genealogie.ravenzwaaij.eu/public/js/vendor.min.js.map HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`**

Do you have any idea, where that might come from?

**Comment by fisharebest** [comment] 2020-09-19 21:01
> Do you have any idea, where that might come from?

The `.map` files are only present during development.  They are large and unnecessary for end users.

If you want them, you'll need to install the source code, and build them using `npm install; npm run production`.

**Comment by Lars1963** [comment] 2020-09-19 21:21
I don't want them, but it then seems there is a unnecessary call for that file somewhere in the productioncode. Or am I mistaken?

**Comment by fisharebest** [comment] 2020-09-20 06:44
> here is a unnecessary call for that file somewhere

When you activate the developer tools in the browser, it will search for `.map` file for certain minified source files.

If it finds them, it can display the original code in the debugger.
If not, it shows the miniifed code in the debugger.

If the file is not found, it is not an error.
