### ISSUE TITLE
Error using CONT tags in NOTEs to NAME

### ISSUE THREAD

**Issue by StuartGregory** [fisharebest/webtrees#767] opened 2015-11-24 15:12 UTC
Using 3 CONT tags in a 2 NOTE for NAME causes error in display and in subsequent Edit screen. The error displayed is:

#0 /edit_interface.php:2521 ErrorException("Undefined offset: 2")
#1 /edit_interface.php:1643 Fisharebest\Webtrees\print_indi_form()

Level 3 CONT tags in 2 NOTEs for other EVENts or FACTs are accepted.

**Comment by fisharebest** [comment] 2015-11-24 16:31
Dupe of #690 and #704 

If you can't wait for the next release, it's a one line (one character!) change.

`$cmatch[2]` should be `$cmatch[1]`

See https://github.com/fisharebest/webtrees/commit/8db5c3f1f4e3b57822113cf45b457c51bb37f38a

**Closed by fisharebest** 2015-11-24 16:31 UTC
