### ISSUE TITLE
2.0: Fact/Event Source Loses Carriage Return after an Image

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#1907] opened 2018-09-14 19:24 UTC
In 2.0, there is no longer a carriage return after a source's image if there is a subsequent source within the same event on the Facts and Events tab.

1.7.11 (http://genealogy.dbq-andersons.com/individual.php?pid=I45&ged=scrubbed-tree)
![image](https://user-images.githubusercontent.com/43183321/45570816-b387ee00-b829-11e8-92b2-bb6df1537aa6.png)

2.0.0-alpha.2 (http://www.dbq-andersons.com/genealogy/webtrees2-public/index.php?route=individual&xref=I45&ged=scrubbed-tree#tab-personal_facts)
![image](https://user-images.githubusercontent.com/43183321/45570779-9a7f3d00-b829-11e8-989d-962281d390a8.png)

Thanks,

Bill

**Comment by fisharebest** [comment] 2018-09-16 13:51
This is using a `float` to position the image and its text.

We should replace this with a flexbox.

**Comment by fisharebest** [comment] 2019-10-28 19:28
Dupe of #2502

**Closed by fisharebest** 2019-10-28 19:28 UTC
Labels: bug
