### ISSUE TITLE
Shared NOTE first line []() printed on site - wt 2.0.11-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3605] opened 2020-11-24 17:52 UTC
**Shared Note N182 of I7206** in the Shared notes List and in the Shared note's title - wt version 2
`[Sisters across the Gulf of Finland](https://www.youtube.com/watch?v=PP9p97Li3Z8)` by Imbi Paju

In pre wt version 2
Sisters across the Gulf of Finland by Imbi Paju

The Source text is
`[Sisters across the Gulf of Finland](https://www.youtube.com/watch?v=PP9p97Li3Z8)` by Imbi Paju

I have updated some notes and I do no longer see the bad texts for these Notes.
The problem is that I do not know how to retrieve all the Notes or other records that may have this issue. 

Source Notes have this issue #3604
It seems to me that Individual, Family, Media or any other note URLs do not have this issue, but I am not sure.

**Comment by fisharebest** [comment] 2021-03-05 11:46
I think this is a duplicate of #2600

**Closed by fisharebest** 2021-03-05 11:46 UTC
