### ISSUE TITLE
Sorting Upcoming events wrong

### ISSUE THREAD

**Issue by HeadGrand** [fisharebest/webtrees#1181] opened 2017-01-07 13:56 UTC
After the last(I'm not sure) the sorting of the tabel of Upcoming events is wrong.  The select option is "sort by date". But the table is sorting first  for the year and then the day.
In my opinion it should sort it only after the day.

![image](https://cloud.githubusercontent.com/assets/13827113/21742167/7b0ba2e4-d4e9-11e6-916c-5ff8ca4e2ae2.png)

Kind Regards
Stephan

**Comment by mpwt** [comment] 2017-01-07 19:25
This problem is known. Look [here](https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/31789-sorting-in-the-box-upcoming-events#62244) in the forum.

**Comment by fisharebest** [comment] 2017-02-03 16:05
I believe this has already been fixed.

The fix will be included in the next release.

**Closed by fisharebest** 2017-02-03 16:05 UTC

**Comment by luca74** [comment] 2020-01-17 21:12
The problem is present in version 2.0.1
